### PR TITLE
NEXUS-4668: Make integrated Maven Indexer extensible (again).

### PR DESCRIPTION
**Pull request by cstamas**
This will be needed by Stuart soon.

### CODE REVIEW

**Comment by velo** [comment]
So, now people can index SWCs, nice
+1

**Comment by cstamas** [comment]
Started feature build:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/82/

**Comment by bdemers** [comment]
+1, but clean the imports

**Comment by cstamas** [comment]
I hastily merged, but just for the record: CI voted +1 too, at least linux slave did, while win slave is 0xdeadbeef:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/82/

**Pull request merged**
