### PR TITLE
REVIEW [NEXUS-5037] single quote password does not work

### PR DESCRIPTION
**Pull request by kellyrob99**
https://issues.sonatype.org/browse/NEXUS-5037

Just apply existing unescape mechanism for password when creating a new user

### CODE REVIEW

**Comment by jdillon** [comment]
+1 ( i hate that we have to do this, but IIUC we don't have anything better atm )

**Comment by kellyrob99** [comment]
+1 by CI https://bamboo.zion.sonatype.com/browse/NXO-OSSF64-3

**Comment by adreghiciu** [comment]
UT/IT checking that problem was solved?

**Comment by kellyrob99** [comment]
I spent a fair bit of time trying to get a working test for this, but it's proving hard to inspect the password value during testing. Any suggestions you might have @adreghiciu would be appreciated.

**Comment by jdillon** [comment]
I do not think we need a IT for this.  We've done this in the past for each tiny change and its produced the testsuite we have now that takes forever.

We should be able to know that use of HtmlUnescapeStringConverter as used in this context (since lots of other stuff doing the same thing) works properly.  We don't need to bloat the testsuite with ~30s additional time to execute with trivial stuff like this.

@kellyrob99 if you want to make a UT that is fine, though what would the UT be testing? the abstract resource or the converter used in the model?  I suggest its the converter and how its generally used in models like this.  I pray there are already UT for it.

**Comment by adreghiciu** [comment]
I wold like the IT not proving that currently the solution works but more that we do not introduce a regression.
@kellyrob99 I would use teh new IT support, create a user with a password containing a single quote and then create a new nexus client using the new user + make a request to nexus using that client. if password would not work it will fail.

**Comment by adreghiciu** [comment]
+1 in rest

**Comment by jdillon** [comment]
/me shrugs ... this code will get thrown away in the not so distant future so way your time spent on this in that light.

**Comment by kellyrob99** [comment]
New IT added and +1 by CI https://bamboo.zion.sonatype.com/browse/NXO-OSSF64-5

**Pull request merged**
