### PR TITLE
[NEXUS-5055] Use local cached artifacts instead of going remote to Central to avoid failures in case Central cannot be accessed

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/352/

**Comment by cstamas** [comment]
:beer:

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Comment by adreghiciu** [comment]
CI voted +1 (failures are unrelated)

**Pull request merged**
