### PR TITLE
[NEXUS-5197] Avoid NPE in member change detection

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by nabcos** [comment]
+1

**Comment by nabcos** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/413/

**Comment by peterlynch** [comment]
a unit test to prove no NPE?

**Comment by peterlynch** [comment]
need to update surefire config to run the new 'Abstract' tests before merging this. punting for later in 2.2 cycle for now.

**Comment by adreghiciu** [comment]
+1

**Comment by peterlynch** [comment]
needs a change to surefire config, or needs me to rename the test

**Comment by peterlynch** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-feature/41

**Comment by peterlynch** [comment]
CI+1 ( 1050 tests )

**Pull request merged**
