### PR TITLE
Add ShutdownHelper so we can delegate std-java or jsw implementations to...

### PR DESCRIPTION
**Pull request by jdillon**
... exit/halt

https://issues.sonatype.org/browse/NXCM-4643

### CODE REVIEW

**Comment by ifedorenko** [comment]
+1

**Comment by peterlynch** [comment]
Any reason not to call WrapperManager.hasShutdownHookBeenTriggered() somewhere?

**Comment by jdillon** [comment]
@peterlynch Where would you put it?

**Comment by peterlynch** [comment]
+1

I looked into WrapperManager code, it looks like calling stop will do the right thing - and we no longer call System.exit() anymore with these changes.

**Comment by peterlynch** [comment]
this change has support and we desire grid stability ;) merging..

**Pull request merged**
