### PR TITLE
[NEXUS-4339] Throw a resource exception also for 403, so expected html i...

### PR DESCRIPTION
**Pull request by adreghiciu**
... sent back to UI

Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by velo** [comment]
also would be nice to trigger a feature build for this one...

**Comment by adreghiciu** [comment]
@peterlynch The upload of artifacts is heavily  tested in Nexus ITs. The only diff is the returned HTML that now contains an <error/> tag. I will look into adding a check that the error tag is present to one of the tests

**Comment by adreghiciu** [comment]
Started feature build https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/169/

**Comment by cstamas** [comment]
:cake:

**Comment by adreghiciu** [comment]
CI votes +1

**Comment by velo** [comment]
+1

**Pull request merged**
