### PR TITLE
[NXCM-4530] Fix logging in "repository not found" while iterating member of a group

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://bamboo.zion.sonatype.com/browse/NXO-OSSF27-1

**Comment by ifedorenko** [comment]
+1

**Comment by adreghiciu** [comment]
CI :+1:

**Comment by cstamas** [comment]
+1

Note: With this change we are muting a problem caused by something else (probably concurrent configuration changes?)

**Comment by adreghiciu** [comment]
We are not muting it. Is still logged at WARN level

**Pull request merged**
