### PR TITLE
Drop capabilities from nexus core

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by nabcos** [comment]
+1

**Comment by cstamas** [comment]
:beer:

But, none of the OSS bundle (nexus-core-webapp or nexus-core-oss-webapp) will include the new capabilities plugin? Asking, since it was included with previous versions

**Comment by nabcos** [comment]
true, capabilities should be included in OSS bundles IMO.

**Comment by velo** [comment]
+1

**Pull request merged**
