### PR TITLE
Add new methods that allows creation of repositories with specified artifact/metadata max age

### PR DESCRIPTION
**Pull request by adreghiciu**
Still, keep the old behavior that was not setting this values to not break existing ITs

Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by nabcos** [comment]
+1

**Comment by cstamas** [comment]
Note: this will work in current (broken) way, and "use default" implies defaults will be applied which the value `0` is not.

Maybe something like "backward compat and broken" ?

**Comment by nabcos** [comment]
Just rename it to USE_BROKEN =D

**Comment by cstamas** [comment]
+1 with rename :D

**Pull request merged**
