### PR TITLE
[NEXUS-4702] rename logback-default and add "Do not touch" headers

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by nabcos** [comment]
maybe also write 'edit logback-nexus.xml instead'?

+1 otherwise

**Comment by adreghiciu** [comment]
That was the text suggested by rich. I copy pasted.

**Comment by cstamas** [comment]
:kiss:

**Comment by adreghiciu** [comment]
Started feature build https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/170/

**Comment by adreghiciu** [comment]
The CI build gave some errors but they do not seem related to log names changes, so I consider it a +1

**Pull request merged**
