### PR TITLE
Add js helpers from usertoken

### PR DESCRIPTION
**Pull request by jdillon**
Adds bits used by usertoken to oss core:
- Ext.define
- Nexus.messages
- Ext.Image
- String.startsWith
- String.endsWith
- Ext.CallbackRef
- Nexus.currentUser

### CODE REVIEW

**Comment by peterlynch** [comment]
is this needed for 2.3?

**Comment by jdillon** [comment]
No it can wait until 2.4

**Comment by peterlynch** [comment]
+1 for 2.4

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
+0 (+1 for moving but too low Est js knowledge to review changes)

**Pull request merged**
