### PR TITLE
[NEXUS-4612] Change default routing patterns

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by cstamas** [comment]
Nice and clean and dandy! :beer:

Btw, what formatter did you use on that XML? ;)

**Comment by velo** [comment]
+1

**Comment by adreghiciu** [comment]
I've run the its feature (https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/121/) but it failed with unrelated tests

**Comment by cstamas** [comment]
Bah, "Unable to locate resource in repository org.apache.maven.wagon.ResourceDoesNotExistException"

Is it possible two jobs were running against same workspace?

**Pull request merged**
