### PR TITLE
[NXCM-4170] Avoid deadlocks by eagerly initializing temp/config directories

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
:coffee:

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/343/

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/346/

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/348/

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
CI 348 voted +1

**Pull request merged**
