### PR TITLE
Add support methods for creating and using nexus client

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
:beer:

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/393/

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
CI voted +1

**Pull request merged**
