### PR TITLE
NEXUS-4595: add a filter to request LDAP server

### PR DESCRIPTION
**Pull request by alecharp**
Add a field in LDAP Plugin to filter the user requests

### CODE REVIEW

**Comment by bdemers** [comment]
Sweet!  At first glance it looks good.  I'll take a closer look in a bit.
Can you add a test for it ?

**Comment by alecharp** [comment]
I will work on it

## 

Adrien Lecharpentier

2011/11/9 Brian Demers <
reply@reply.github.com>

**Comment by alecharp** [comment]
I added tests, maybe not enough. If it needs more, just tell me

**Comment by nabcos** [comment]
see https://github.com/sonatype/nexus/pull/70

**Pull request closed without merging**
