### PR TITLE
Signed the jar with our new key. Good until 9/7/2014

### PR DESCRIPTION
**Pull request by brianf**

### CODE REVIEW

**Comment by brianf** [comment]
D:\svn\nexus\nexus\nexus-webapp\src\main\webapp>"c:\Program Files\Java\jdk1.6.0_
23\bin\jarsigner" -verify -verbose -certs digestapplet.jar

```
     435 Fri Sep 12 17:55:12 EDT 2008 META-INF/MANIFEST.MF
     556 Wed Feb 08 13:36:30 EST 2012 META-INF/SONATYPE.SF
    4715 Wed Feb 08 13:36:30 EST 2012 META-INF/SONATYPE.RSA
       0 Fri Sep 12 17:54:34 EDT 2008 META-INF/
```

sm      6022 Fri Sep 12 17:29:18 EDT 2008 digestapplet.jar

```
  X.509, CN="Sonatype, Inc", OU=Engineering, O="Sonatype, Inc", L=Silver Spr
```

ing, ST=MD, C=US
      [certificate is valid from 9/7/11 6:30 PM to 9/7/14 6:30 PM]
      X.509, SERIALNUMBER=07969287, CN=Go Daddy Secure Certification Authority,
OU=http://certificates.godaddy.com/repository, O="GoDaddy.com, Inc.", L=Scottsda
le, ST=Arizona, C=US
      [certificate is valid from 11/15/06 8:54 PM to 11/15/26 8:54 PM]
      [KeyUsage extension does not support code signing]
      X.509, OU=Go Daddy Class 2 Certification Authority, O="The Go Daddy Group,
 Inc.", C=US
      [certificate is valid from 6/29/04 1:06 PM to 6/29/34 1:06 PM]

```
       0 Fri Sep 12 17:25:10 EDT 2008 org/
       0 Fri Sep 12 17:25:10 EDT 2008 org/sonatype/
       0 Fri Sep 12 17:25:10 EDT 2008 org/sonatype/nexus/
       0 Fri Sep 12 17:53:22 EDT 2008 org/sonatype/nexus/applet/
```

sm      1188 Fri Sep 12 17:53:22 EDT 2008 org/sonatype/nexus/applet/DigestApplet
$1.class

```
  X.509, CN="Sonatype, Inc", OU=Engineering, O="Sonatype, Inc", L=Silver Spr
```

ing, ST=MD, C=US
      [certificate is valid from 9/7/11 6:30 PM to 9/7/14 6:30 PM]
      X.509, SERIALNUMBER=07969287, CN=Go Daddy Secure Certification Authority,
OU=http://certificates.godaddy.com/repository, O="GoDaddy.com, Inc.", L=Scottsda
le, ST=Arizona, C=US
      [certificate is valid from 11/15/06 8:54 PM to 11/15/26 8:54 PM]
      [KeyUsage extension does not support code signing]
      X.509, OU=Go Daddy Class 2 Certification Authority, O="The Go Daddy Group,
 Inc.", C=US
      [certificate is valid from 6/29/04 1:06 PM to 6/29/34 1:06 PM]

sm      1668 Fri Sep 12 17:53:22 EDT 2008 org/sonatype/nexus/applet/DigestApplet
$2.class

```
  X.509, CN="Sonatype, Inc", OU=Engineering, O="Sonatype, Inc", L=Silver Spr
```

ing, ST=MD, C=US
      [certificate is valid from 9/7/11 6:30 PM to 9/7/14 6:30 PM]
      X.509, SERIALNUMBER=07969287, CN=Go Daddy Secure Certification Authority,
OU=http://certificates.godaddy.com/repository, O="GoDaddy.com, Inc.", L=Scottsda
le, ST=Arizona, C=US
      [certificate is valid from 11/15/06 8:54 PM to 11/15/26 8:54 PM]
      [KeyUsage extension does not support code signing]
      X.509, OU=Go Daddy Class 2 Certification Authority, O="The Go Daddy Group,
 Inc.", C=US
      [certificate is valid from 6/29/04 1:06 PM to 6/29/34 1:06 PM]

sm      3226 Fri Sep 12 17:53:22 EDT 2008 org/sonatype/nexus/applet/DigestApplet
.class

```
  X.509, CN="Sonatype, Inc", OU=Engineering, O="Sonatype, Inc", L=Silver Spr
```

ing, ST=MD, C=US
      [certificate is valid from 9/7/11 6:30 PM to 9/7/14 6:30 PM]
      X.509, SERIALNUMBER=07969287, CN=Go Daddy Secure Certification Authority,
OU=http://certificates.godaddy.com/repository, O="GoDaddy.com, Inc.", L=Scottsda
le, ST=Arizona, C=US
      [certificate is valid from 11/15/06 8:54 PM to 11/15/26 8:54 PM]
      [KeyUsage extension does not support code signing]
      X.509, OU=Go Daddy Class 2 Certification Authority, O="The Go Daddy Group,
 Inc.", C=US
      [certificate is valid from 6/29/04 1:06 PM to 6/29/34 1:06 PM]

  s = signature was verified
  m = entry is listed in manifest
  k = at least one certificate was found in keystore
  i = at least one certificate was found in identity scope

jar verified.

**Comment by velo** [comment]
++

**Comment by cstamas** [comment]
:beer:

**Comment by nabcos** [comment]
+1

**Comment by mcculls** [comment]
+1

**Pull request merged**
