### PR TITLE
Switch to shiro-guice configuration plus noSessionCreation

### PR DESCRIPTION
**Pull request by mcculls**
Kicked off first round of CI: https://builds.sonatype.org/job/nexus-oss-its-feature/318/

### CODE REVIEW

**Comment by cstamas** [comment]
:beer:

Yes! Empty web.xml, finally!

**Comment by nabcos** [comment]
+1

**Comment by mcculls** [comment]
First round of CI looks good: https://builds.sonatype.org/job/nexus-oss-its-feature/318/

**Comment by peterlynch** [comment]
+1 with faith

**Comment by mcculls** [comment]
Latest CI: https://builds.sonatype.org/job/nexus-oss-its-feature/326/

**Pull request merged**
