### PR TITLE
o [NEXUS-4656] Unstable IT: Don't start and stop proxy repo server to change error behavior

### PR DESCRIPTION
**Pull request by nabcos**
The first connection to nexus will initialize the http client and kick
off the status checker thread. This thread will request "/", and as this
IT was previously shutting down the proxy repo server right after the
first download, it often ran into 'Connection refused'.

Changed to not bounce the jetty acting as the remote server being proxied to change between content delivery and different error codes.

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by velo** [comment]
++

**Comment by mcculls** [comment]
+1

**Comment by nabcos** [comment]
windows VM is completely broken, but linux passed:
https://builds.sonatype.org/job/nexus-oss-its-feature/jdk=java-6x,label=linux/65/

**Pull request merged**
