### PR TITLE
[NXCM-4396] Improve error message when encryption fails.

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NXCM-4396

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
Wasn't the agreement to move new/old settings stuff out from this plugin?
It already got globally deprecated:
https://github.com/sonatype/nexus/commit/3a91f5b7316cb791473173bb2b50e418cf97a88b

And I believe this affects the settings too, that descends from this class?

**Comment by peterlynch** [comment]
yes - not sure there was a jira for creating new plugin for settings though - so I created one

https://issues.sonatype.org/browse/NXCM-4418

actually thought @jdillon was inspired the other day to start this but whoever - please proceed soon

**Comment by jdillon** [comment]
@cstamas it was easier to look at fixing the issues that @adreghiciu found before doing any larger scale refactoring (ie transplanting the functionality to another project).

**Comment by cstamas** [comment]
Ok, just was wondering this morning how these changes related to the fact that _whole plugin_ (not only some Mojos from it) was deprecated :)

**Comment by jdillon** [comment]
@cstamas so is nexus-maven-plugins project going to stay around for a while, I thought you were going to move staging bits into nexus-staging-plugin or something.  Did you change your mind and/or defer that for later?

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
+1 lets merge this and proceed with working on https://issues.sonatype.org/browse/NXCM-4418

**Pull request merged**
