### PR TITLE
Minimum changes to disable (for moving out) capabilities plugin

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by adreghiciu** [comment]
Decision was taken on a call that we will further developing capabilities plugin into own git repo and disable teh module in core

**Comment by jdillon** [comment]
+1

**Comment by rseddon** [comment]
+1

**Comment by brianf** [comment]
+0, there's a vote ;-)

**Comment by nabcos** [comment]
+1

**Comment by bdemers** [comment]
+1 but we need to add the ITs (or similar ITs) back when this is merged back to master

**Pull request merged**
