### PR TITLE
Changing the bundle name from nexus-oss-webapp to nexus-core-oss-webapp ...

### PR DESCRIPTION
**Pull request by bdemers**
...and the war, nexus-webapp to nexus-core-webapp

### CODE REVIEW

**Comment by adreghiciu** [comment]
So what happens to "nexus-oss-webapp"? will there be created from other place and include insight plugin?

**Comment by peterlynch** [comment]
honestly a little fuzzy on these name changes and 1433 changed files doesn't help me.

If this change implements what was discussed  in scrums then +1

**Comment by bdemers** [comment]
@peterlynch, I agree, ultimately the 1,433 files have changed, since one of the parent directories had been moved.

**Comment by velo** [comment]
+1

**Comment by nabcos** [comment]
+1433

**Pull request merged**
