### PR TITLE
NEXUS-4692: Use HttpClient4x as default transport

### PR DESCRIPTION
**Pull request by cstamas**
Changes in:
- Alin's original plus the missing "boxed config" changes
- Config version bumped to force upgrade, new upgrader
- UT resource updates

These changes covers the OSS part, non-OSS editions still has pending changes.

### CODE REVIEW

**Comment by cstamas** [comment]
CI
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/379/

**Comment by adreghiciu** [comment]
@cstamas why we do not keep the configuration version in sync with first nexus version it uses it?
E.g. in this case the new version of configuration to be 2.2?

**Comment by cstamas** [comment]
I was thinking about it, but there were some statements flying in and out, that master will contain 2.1.1 then whoknows what and ultimately what version will master become, as we saw that with RC1 fiasco too.

But I agree, and will bump the config version from 2.0.1 to 2.2.0

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by adreghiciu** [comment]
Do we have a successful CI feature build with all the changes?

**Comment by peterlynch** [comment]
+1 but we need to jigger a bunch of CI jobs when this gets merged ( provide job specific to executing http client 3 instead of 4)

**Comment by peterlynch** [comment]
and we need a successful CI feature job before that

**Comment by cstamas** [comment]
CI
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/386/

**Comment by cstamas** [comment]
CI Win voted +1 but CI Linux had some strange (and I think unrelated) test failure:
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/386/

**Comment by adreghiciu** [comment]
Unrelated. That is a bug we solved in the non merged launcher improvements branch

**Comment by peterlynch** [comment]
Trying again https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/389/

**Comment by peterlynch** [comment]
feature build failed because jetty 7 and SelectChannelConnector hung the IT- need to remerge master and try again

**Comment by cstamas** [comment]
Rebased against master, and kicking another CI job

**Comment by cstamas** [comment]
CI kicked:
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/391/

**Comment by cstamas** [comment]
CI linux passed. CI win failed with some (unrelated) bootstrap test: ShutdownIfNotAliveThreadTest

**Comment by adreghiciu** [comment]
@cstamas go on and merge

**Pull request merged**
