### PR TITLE
New theme

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by velo** [comment]
Do you have a screen shot for us? =D

**Comment by bdemers** [comment]
Just attached them to the issue

**Comment by velo** [comment]
+1

**Comment by peterlynch** [comment]
Could you attach a screenshot of what it looks like without a license installed? I am curious if the links to upgrade are no longer browser default 'blue' and 'purple'. It doesn't look like the changes here would fix those. IMO that will look horrible and unreadable.

**Comment by bdemers** [comment]
I attached them to the issue

**Comment by peterlynch** [comment]
Thanks for adding screenshots. Look good. 

What about he 'followed link' color?

+1

**Comment by bdemers** [comment]
@peterlynch same as the screen shots

**Comment by bdemers** [comment]
Merged manually

**Pull request closed without merging**
