### PR TITLE
[NXCM-4737] hack in query-string customizations via QueryStringBuilder s...

### PR DESCRIPTION
**Pull request by jdillon**
...o that remote browsing secure.central gets the proper request paramemters.

https://issues.sonatype.org/browse/NXCM-4737

### CODE REVIEW

**Comment by jdillon** [comment]
As noted in FIXME comment, this support should probably be done automatically in AhcProvider.  Though as I was not even aware AHC was in use anymore, to avoid potentially breaking something else I've limited this change only to rrb.

**Comment by jdillon** [comment]
https://builds.sonatype.org/job/nexus-oss-its-feature/430/ FAILED in license headers (otherwise all other bits passed)

**Comment by peterlynch** [comment]
wondering about a test..not sure since ahc goes away soon?

otherwise +1

**Comment by jdillon** [comment]
There was not already a generic test for the class this lived in, and I didn't see too much value in making one just to add this additional test.  We already have tests for the builder used here, and I don't think we need to test if AHC works, and as you noted it should go away anyways.

**Comment by nabcos** [comment]
+1, not pretty but as long as we're waiting for https://issues.sonatype.org/browse/NEXUS-4689 ...

**Comment by jdillon** [comment]
BTW, if the changes to HttpClientUtil to configure() release() are made public, then we could really re-implement this using httpclient4 w/o much problem.

**Pull request merged**
