### PR TITLE
Catch-All fix

### PR DESCRIPTION
**Pull request by cstamas**
Removal of "special catch-all" permission, and doing checks instead of PlexusResources on the fly.

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
Looks okay to me :sake:

**Comment by cstamas** [comment]
Just FTR: checked Shiro Filter implementation and here what happens: resources are "handled" as they are discovered (by Plexus collection lookup) as this:

```
NexusApplication#handlePlexusResourceSecurity(PlexusResource) calls
org.sonatype.security.web.DefaultProtectedPathManager calls
org.apache.shiro.web.filter.mgt.DefaultFilterChainManager.class calls
org.apache.shiro.web.filter.PathMatchingFilter
```

Finally, Shiro in `PathMatchingFilter` keeps path patterns from descriptors as plain String in a map. On incoming request, it uses this same `org.apache.shiro.util.AntPathMatcher` to match the pattern in a map against `request.getRequestURI()` (with some spice). Meaning, we should get the very same results wrt this sanity check as Shiro.

**Comment by cstamas** [comment]
CI
https://bamboo.zion.sonatype.com/browse/NXO-OSSF38-1

**Comment by nabcos** [comment]
+1

**Comment by cstamas** [comment]
CI +1'd it, merging it.

**Pull request merged**
