### PR TITLE
[NEXUS-5246] Use status 307 (temporary redirect) instead of 301 (permanent redact) to avoid browser caching

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/409/

**Comment by nabcos** [comment]
+1, but you should drop the NEXUS-5212-related commits from this branch.
(git rebase -i master)

**Comment by peterlynch** [comment]
This should not have got merged, feature build failed

**Comment by nabcos** [comment]
yes, apparently I looked at the wrong build while going through the pull requests yesterday. I committed the fix already, oss-its are running.
https://builds.sonatype.org/job/nexus-oss-its/420

**Comment by nabcos** [comment]
linux passed, win failed with an unrelated error (search/indexer related)

**Comment by peterlynch** [comment]
looks good

**Pull request merged**
