### PR TITLE
Updated about page to accept contributions from plugins

### PR DESCRIPTION
**Pull request by dbradicich**
Simply fires event to capture any changes to the about html that a plugin may want to make

### CODE REVIEW

**Comment by velo** [comment]
+1

**Comment by bdemers** [comment]
+1 the change looks fine, just make sure it works with PRO, a

**Comment by dbradicich** [comment]
yes definitely validated with pro, pro simply overrides the getHelpText() method, so the existing use is covered fine

**Comment by bdemers** [comment]
:+1:

On Wed, Feb 1, 2012 at 12:39 PM, Damian Bradicich
reply@reply.github.com
wrote:

**Pull request merged**
