### PR TITLE
o [NXCM-4362] Fix error dialog message on password change

### PR DESCRIPTION
**Pull request by nabcos**

### CODE REVIEW

**Comment by peterlynch** [comment]
So we will always get a useful error message in the response? I am thinking the http status was included before because sometimes there was not an otherwise useful message from backend ( 500 error ?) . Maybe display the http status if we can determine there is nothing user friendlier in the response.

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
server status line will now always be displayed when no message was extracted from the error response.

**Comment by peterlynch** [comment]
+1

**Comment by cstamas** [comment]
+1

**Pull request merged**
