### PR TITLE
o [NEXUS-4579] Option for snapshot removal task to delete immediately or move to trash

### PR DESCRIPTION
**Pull request by nabcos**
Backporting Snapshot Remover Tasks changes. Unchanged code but for one place regarding plexus/slf4j logger.

IT passes locally, I will try manually sometime tomorrow (separate +1 ;)

### CODE REVIEW

**Comment by bdemers** [comment]
+1 if the only changed bits was the logger

**Comment by cstamas** [comment]
What are those full file changes? Are we sneaking in bad line-endings?

**Comment by nabcos** [comment]
that was pre- & post-'big EOL change commit'. The cherry-pick went without conflict (aside from logger) when I was converting the EOL for the touched files... you can see the detailed changes in the second commit, the first commit is only changing EOL.

**Comment by cstamas** [comment]
+1

PS: (facepalm) i just realized this is merge into nexus-1.9.2.x, not master!

**Comment by nabcos** [comment]
tested manually with 1.9.2.4-SNAPSHOT -> +1

**Pull request merged**
