### PR TITLE
NEXUS-4627: downgradeable locks

### PR DESCRIPTION
**Pull request by cstamas**
This pull request contains following:
- merge of Stuart's change wrt "downgrades", making it actually happening
- added two tests (one for Nexus' SimpleResourceLock and one for SISU Local locks) verifying downgrade _is happening_.
- adjusted existing SimpleLockResourceLRTest wrt it's -- obsolete now -- expectations about locks _not downgrading_.

This pull is just here to be reviewed, is not to be merged yet, since local validation still remains!

Latest what happened:
- rebase against _latest master_ since it has build problems fixed.
- build of this branch _UT/IT_ passes locally on my mac

### CODE REVIEW

**Comment by velo** [comment]
deja vu?

**Comment by cstamas** [comment]
Rebased against finally fixed master (first the content validation, then the "slow ITs" with waitForAllTasks).

Submitting the rebased branch for CI build
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/

**Comment by cstamas** [comment]
Job 47 started https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/47/

**Comment by cstamas** [comment]
So, results:

CI win and linux slaves likes it:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/47/

My mac likes it

Then, let's vote, and put this baby into core. But in a moment it's in core, we should push Nexus to the limits with testing.

**Comment by adreghiciu** [comment]
If tests are passing, what can I say? +1

**Comment by velo** [comment]
+1

**Pull request merged**
