### PR TITLE
REVIEW: [NXCM-5196] Read version from "/META-INF/nexus/nexus-bundle.properties" ...

### PR DESCRIPTION
**Pull request by adreghiciu**
...if file is available (only in bundles build by nexus-bundles project). Otherwise, fallback to maven pom.properties (as before)

https://issues.sonatype.org/browse/NXCM-5196
https://bamboo.zion.sonatype.com/browse/NXO-OSSF27

### CODE REVIEW

**Comment by nabcos** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Comment by adreghiciu** [comment]
CI :+1: https://bamboo.zion.sonatype.com/browse/NXO-OSSF49-3

**Comment by ifedorenko** [comment]
The issue was deferred, no immediate plans to work on this.

**Pull request closed without merging**
