### PR TITLE
NEXUS-4627: Downgradeable locks

### PR DESCRIPTION
**Pull request by cstamas**
This pull request contains following:
- merge of Stuart's change wrt "downgrades", making it actually happening
- added two tests (one for Nexus' SimpleResourceLock and one for SISU Local locks) verifying downgrade _is happening_.
- adjusted existing SimpleLockResourceLRTest wrt it's -- obsolete now -- expectations about locks _not downgrading_.

This pull is just here to be reviewed, is not to be merged yet, since local validation still remains!

### CODE REVIEW

**Comment by cstamas** [comment]
Just note: this branch locally built fails with ITs, still unsure why (master has problems too and it was spinned from it this morning!). Will report back when I know more.

**Comment by cstamas** [comment]
Getting the same problems as last CI build had:
https://gist.github.com/e08bc1f9f4b3f920f5bc

Meaning, the master branch this branch was spin off already had the problems. Will wait for morning to have these issues resolved. No other problems detected after multiple subsequent builds.

**Comment by velo** [comment]
I'm happy not that are tests +1
Not happy that CI is no passing, but I assume code review != test passing....

**Comment by cstamas** [comment]
CI was not passing, since this branch was spawned from master in a moment your change wrt enabled content validation was merged already, but all those "fake XML" and "fake JAR" fixes was not in place yet. Will close this pull also, rebase, and after successful local build will reopen it.

**Pull request closed without merging**
