### PR TITLE
[NXCM-4046] Remove logback.xml included as resource, this is included in...

### PR DESCRIPTION
**Pull request by jdillon**
... the conf/ dir in the assembly and causes logback to complain.

https://issues.sonatype.org/browse/NXCM-4046

### CODE REVIEW

**Comment by jdillon** [comment]
build passed https://builds.sonatype.org/job/nexus-oss-its-feature/296/

**Comment by cstamas** [comment]
What happens now with the logging when Nexus deployed as WAR?

**Comment by jdillon** [comment]
depends I suppose on where its deployed, if logback is already initialized, etc.

**Comment by peterlynch** [comment]
guess we don't understand why it was added in first place @cstamas

**Comment by jdillon** [comment]
IIUC it was added because the logback jars were exposed in the boot lib so that jetty can use the same logging.  And it needed a configuration file to control how it was initialized.

Removing it from the war avoids WARN and thus logback dumping its bootstrap logging details when Nexus boots.  When users are embedding via war they can sort out how to deal with whatever logging system the container they deploy into is using to get any bootstrap messages they want/need out.

**Comment by cstamas** [comment]
This is wrong change. Read my full comment on ML.

**Comment by jdillon** [comment]
well then fix it, I don't have time to read books you write in emails.  just fix it

**Comment by cstamas** [comment]
Fix in [pull request 370](https://github.com/sonatype/nexus/pull/370)

Closing this pull.

**Pull request closed without merging**
