### PR TITLE
NXCM-3809 artifactory bridge

### PR DESCRIPTION
**Pull request by velo**
Moved artifactory migration bits BACK to it's own github repository.
https://github.com/sonatype/nexus-migration-plugin/commit/015ac10b61266c7ffeada73c22a98a489bbf4a5c

Changed test-harness bits to allow testing migration bridge.
https://github.com/sonatype/nexus-bundles/pull/5

Also merged stuart fix to jetty.xml in
https://github.com/sonatype/nexus/pull/249

### CODE REVIEW

**Comment by mcculls** [comment]
Note that https://github.com/sonatype/nexus/pull/261 is apparently the favoured solution for NXCM-3808

**Comment by mcculls** [comment]
+1

**Comment by nabcos** [comment]
+1 after NXCM-3808 is sorted out

**Comment by velo** [comment]
Merged NXCM-3808 from tamas, all went ok!

**Pull request merged**
