### PR TITLE
NEXUS-4938 - Add createThisReference() to ReferenceFactory

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by velo** [comment]
https://github.com/sonatype/sisu-restlet-bridge/pull/1

**Comment by nabcos** [comment]
are we still enforcing the 'no snapshots in master' policy?
otherwise +1

**Comment by cstamas** [comment]
+1

@nabcos I did continue using that in my pull requests... And releasing is "cheap" IMO.
@velo do you want me to release the bridge?

**Comment by velo** [comment]
@cstamas your call, I just merged the related pull.

**Pull request merged**
