### PR TITLE
Use sisu-goodies 1.5.1-SNAPSHOT (has the event bus fixes)

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
https://bamboo.zion.sonatype.com/browse/NXO-OSSF33-1

**Comment by adreghiciu** [comment]
CI :+1:

**Comment by peterlynch** [comment]
we can just release and depend on that version

**Comment by peterlynch** [comment]
I released sisu-goodies 1.5.1 and changed nexus to depend on that

**Pull request closed without merging**
