### PR TITLE
[NXCM-3564] HTTP Client 4.x remote storage implementation fixes

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by adreghiciu** [comment]
Started feature CI build: https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/136/

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
CI build failed. Started a new one: https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/138/

**Comment by adreghiciu** [comment]
138 Build was Okay on linux. Win failed to build at all. Consider a +1

**Comment by cstamas** [comment]
:beer:

**Pull request merged**
