### PR TITLE
Drop nexus-siesta-test-plugin from bundle

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
CI build: https://bamboo.zion.sonatype.com/browse/NXO-OSSF21-1

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
+1, don't forget to update nexus-bundles testsuite once this is merged.

**Comment by adreghiciu** [comment]
CI :+1:

**Pull request merged**
