### PR TITLE
Update to app-lifecycle 1.6

### PR DESCRIPTION
**Pull request by jdillon**

### CODE REVIEW

**Comment by cstamas** [comment]
:beer:

**Comment by nabcos** [comment]
+1

**Comment by velo** [comment]
Are we sure that is safe just a week before release?

+1 after CI says it is all OK

**Comment by bdemers** [comment]
+1

**Comment by jdillon** [comment]
@velo This is a fairly safe change.  Currently nexus-oss uses version 1.5, and nexus-pro uses 1.4, 1.6 only adds additional configuration for pluginName, pluginDescription and pluginSiteUrl.

**Pull request merged**
