### PR TITLE
[NEXUS-4692] Make http client 4 default client

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/371/

**Comment by cstamas** [comment]
+1

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
CI voted +1

**Pull request merged**
