### PR TITLE
[NXCM-4607] Implement REST resource/nexus client for locking/unlocking resources

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
+1 but: lockType: why not an enum or provide constants at least?

**Comment by adreghiciu** [comment]
@cstamas that will be better. Yet I did not wanted to import whole nexus just to get the Action enum

**Comment by adreghiciu** [comment]
@cstamas see 4cb00930174fcfb752381cf67fbe8a823c04335f

**Comment by nabcos** [comment]
+1

**Pull request merged**
