### PR TITLE
NEXUS-4916 - add proxy configuration

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by mcculls** [comment]
+1 for code, but would like to see a plugin integration test that exercises the proxy

**Comment by peterlynch** [comment]
I thought the main point was to fix the ITs that did not test that only proxy was used?

**Comment by jdillon** [comment]
If there is a simple way to test w/a proxy to validate, then we should do add it.  But otherwise, I don't think Velo will be doing much more work on this, so merge and move on?

**Comment by adreghiciu** [comment]
+1 merge

**Pull request merged**
