### PR TITLE
Fixing UT to adhere Timeline changes.

### PR DESCRIPTION
**Pull request by cstamas**
Two UTs from TimelineTest failed (rightfully) on Win,
and one was @Ignored. All three of them fixed:
- the two win failures were due to Lucene bump from 3.0 to 3.6.1
  that uses NIO and mmapped files, hence, locks the index files and
  is impossible to "overwrite" then behind the back of Lucene from same
  JVM process (as UT originally did: mangled files of opened lucene index)
- the ignored test was made non-ignored, but placing unsupported
  segment files, that makes index broken (as lucene refuses to read them
  and repair will happen)

All these tests are actually testing state after repair, and doing
reads, additions and purge operations on repaired index.

### CODE REVIEW

**Comment by peterlynch** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by cstamas** [comment]
Was this pull req closed intentionally?

**Comment by jdillon** [comment]
I merged it... or at least I thought I merged it... wtf...

**Pull request merged**
