### PR TITLE
NEXUS-4815 - minor changes to log configuration UI

### PR DESCRIPTION
**Pull request by velo**

### CODE REVIEW

**Comment by nabcos** [comment]
why exactly are we not removing the read only fields?

**Comment by velo** [comment]
It is doable, but with read only fields it is prettier
http://screencast.com/t/cfnyibbrb

Anyway, I can remove....

**Comment by nabcos** [comment]
it's only I remember @rseddon saying the fields should be removed.
But the change is okay -> +1

**Comment by cstamas** [comment]
:cake:

**Pull request merged**
