### PR TITLE
[NXCM-5111,NEXUS-5609] UI fixes for IE

### PR DESCRIPTION
**Pull request by nabcos**
Linked dist has the fixes, should be smoke tested with IE8/9/10.

https://docs.google.com/a/sonatype.com/file/d/0B4rXJy46Zo2WMVI0dEQ5VkZiM0U/edit?usp=sharing

### CODE REVIEW

**Comment by peterlynch** [comment]
...currently having a look at this

**Comment by peterlynch** [comment]
+1 tested IE8 windows XP and IE10 and both  perform as expected. However could not test staging UI - will need a pro build with these changes.

**Comment by jdillon** [comment]
+1

**Comment by kellyrob99** [comment]
+1

**Pull request merged**
