### PR TITLE
Extended UserAgentBuilder to allow its reuse in contexts where a ProxyRe...

### PR DESCRIPTION
**Pull request by bentmann**
...pository is not available but only a RemoteStorageContext (e.g. the global one)

### CODE REVIEW

**Comment by cstamas** [comment]
The method name `formatRemoteRepositoryStorageUserAgentString(RemoteStorageContext)` IMO is wrong, it implies there _is_ a repository involved (RemoteRepositoryStorage exists for Proxy repositories only!). I'd change the method name to something like `formatUserAgentString(RemoteStorageContext)` and then it would be a :beer:

**Comment by bentmann** [comment]
Method name updated as suggested but too bad I'm not into beer :-)

**Comment by cstamas** [comment]
:cake:

**Comment by nabcos** [comment]
:sharapova:
Hm, doesn't work as intended.

**Comment by bentmann** [comment]
LOL

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1 ... this class could also do with a UT

**Comment by bentmann** [comment]
Merged in 4ff31eaec1825af80aafa39b79ca5c538bad6e4b

**Pull request closed without merging**
