### PR TITLE
H2 provider plugin

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-5312

Still pending updating nuget/usertoken + pro which use h2.

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
+1
JFTR: [sonatype/nexus-licensing](https://github.com/sonatype/nexus-licensing) is a candidate to use h2 provider plugin

**Comment by cstamas** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Pull request merged**
