### PR TITLE
NEXUS-4813: eagerly initialize filter pipeline

### PR DESCRIPTION
**Pull request by mcculls**
Scheduled CI build: https://builds.sonatype.org/job/nexus-oss-its-feature/188/

### CODE REVIEW

**Comment by cstamas** [comment]
:beer:

**Comment by nabcos** [comment]
+!

**Comment by adreghiciu** [comment]
I do not disagree with the change but what was the reasoning behind this change?

**Comment by mcculls** [comment]
The original problem is described in NEXUS-4813 - lazily initialising the Guice filter pipeline meant that security wasn't initialised in the Filter's init call, but instead during the doFilter call. Because shiro security is applied before the doFilter pipeline this meant that the first request was implicitly blocked, while subsequent requests went through ok because security had then been setup at that point.

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
CI results: one failure on windows (testGroupReindex) which afaict is an intermittent IT failure

https://builds.sonatype.org/job/nexus-oss-its-feature/188/jdk=java-6x,label=win/testReport/junit/org.sonatype.nexus.index/GroupReindexIndexerManagerTest/testGroupReindex/history/

**Comment by bdemers** [comment]
+1

**Pull request merged**
