### PR TITLE
[NEXUS-5361] Remove CheckSum browse + search applet

### PR DESCRIPTION
**Pull request by jdillon**
https://issues.sonatype.org/browse/NEXUS-5361

### CODE REVIEW

**Comment by jdillon** [comment]
Not really anything that can be verified by a its build... I don't believe there are any specific its for this.

**Comment by cstamas** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Comment by jdillon** [comment]
I guess we want to keep the checksum search, but just kill the digestapplet (which wasn't my original understanding... but oh well).

**Comment by nabcos** [comment]
+1

**Pull request merged**
