### PR TITLE
o [NXCM-4389] Set up favicon cross-browser compatible

### PR DESCRIPTION
**Pull request by nabcos**

### CODE REVIEW

**Comment by peterlynch** [comment]
can we have a test to make sure favicon can be fetched? I think this has regressed a few times since I have worked on Nexus.

**Comment by jdillon** [comment]
.png what browsers use a .png file for favicon?

**Comment by nabcos** [comment]
http://www.kevinleary.net/how-to-add-cross-browser-favicon-website/
-> "Cross Browser Approach" is what I followed

**Comment by nabcos** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/364/

**Comment by peterlynch** [comment]
+1

**Pull request merged**
