### PR TITLE
NEXUS-4943: Generalize metadata handling

### PR DESCRIPTION
**Pull request by cstamas**
The existing "maven metadata manager" concept pulled up a level, with "defaulted" NOOP implementation for now, except in case of M2Repository where a real implementation (merely just delegation to existing calls) added.

### CODE REVIEW

**Comment by jdillon** [comment]
Missing tests?

I took a quick look and nothing negative to say about it ;-)  A few empty/superfluous javadocs (like \@return w/o any text).

What is the example use for implementing the metadata related bits for the SP spec ( https://docs.google.com/a/sonatype.com/spreadsheet/ccc?key=0An3vtHmXvlwXdDUzVG5aMkFCMXE3TmVKd2tEUkUya1E#gid=0 )?

**Comment by cstamas** [comment]
```
  Repository repository = ...
  repository.getRepositoryMetadataManager().expireMetadataCaches( new ResourceStoreRequest("/") );
```

This could be done against any repository, but currently only M2 repositories will do anything (others not implementing this feature will fall back to NOOP manager doing nothing).

**Comment by jdillon** [comment]
Okay, I asked Alin to look this over for sanity.  I think this change is going to be enough to generically cope with metadata muck... 

+1

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
Rebased against latest master.
Added tests, and those tests resulted in a bug discovery and it's fix is in place. 

This also means, that JD owes beer to two of us, as he actually made a good deed by asking for UTs. And people doing good deeds usually give out some beer too. At least, it stems from their "good" nature. They like to do good things to others. So, conclusion is that JD owes 2 beers: one for @adreghiciu and one for me :D

**Comment by cstamas** [comment]
Before anyone starts panicking: it's friday past 6PM here :P

**Pull request merged**
