### PR TITLE
Assign restlet1x plugin low ranking

### PR DESCRIPTION
**Pull request by mcculls**
Kicked off CI: https://bamboo.zion.sonatype.com/browse/NXO-OSSF3-1

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1 Tested the fix and it works

**Comment by nabcos** [comment]
+1

**Comment by mcculls** [comment]
CI voted +1

**Comment by jdillon** [comment]
Are we going to do something about the underlying cause which requires this ranking?  ie. that restlet1x is providing some components which appear to be needed/required by siesta and/or other servlet providing plugins?

Adding the ranking here is a better fix than the original hack for sure, but there is still something else going on with restlet1x which needs to get sorted out so that in the future (not so near future) that this plugin can be removed and everything will still operate properly.

I think the effort to pull out restlet into a plugin and allow servlets to be provided by other plugins wasn't fully implemented... or rather was thought to be fully implemented due to lack of another plugin providing servlets, and now that we have one we seem to have identified that restlet1x is still impacting that plugin when it should not.

**Comment by mcculls** [comment]
Note that this is totally unrelated to the issue about requiring the SecurityFilter, which I'll address in a different email (or pull-request if appropriate). The issue here is that each Nexus plugin with a ServletModule defines a FilterPipeline that is used to decide which servlet should handle an incoming request (this is stock guice-servlet). In Nexus we merge these per-plugin pipelines dynamically into a single MultiFilterPipeline which is then installed into the NexusGuiceFilter subclass - this is necessary to get around the static-ness of the stock GuiceFilter.

This basic setup works fine when there's no overlap between the resource paths served by each plugin. However, the restlet1x plugin defines a 'catch-all' path (ie. /*) which means that if the restlet1x FilterPipeline appears in the MultiFilterPipeline before the FilterPipeline of any other plugins then servlets from those plugins will be hidden by restlet1x because it will match the incoming request first. This is therefore a component ordering issue and has nothing to do with any dependency on restlet1x - the same thing would happen if two new plugins defined servlet paths that overlapped with one another.

In Plexus (and therefore Nexus) plugin injectors are by default given rankings higher than the core (and higher than any previously created plugin injector). This is so they can override selected core components if they wish, as well as components from dependent plugins. Therefore if the restlet1x plugin starts after the siesta plugin then by definition its FilterPipeline will have a higher ranking than the siesta FilterPipeline and will therefore appear before it in the MultiFilterPipeline. The solution is to ensure that the restlet1x FilterPipeline has a lower ranking than the siesta FilterPipeline (regardless of plugin startup) and the easiest way to do this is to assign restlet1x a binding rank of zero, ie. effectively the same as core.

**Comment by jdillon** [comment]
Okay, thanks for the detailed explanation @mcculls :-)

I think what I was hinting at is that restlet1x probably shouldn't have a /\* "catch-all" (and really no plugin should).  If a /\* is needed, then that should probably live in core.  restlet1x probably should be updated to only provide path configurations for bits it actually has/knows about (ie. /service/local/\* /content/\* and unfortunately /index.html, not sure if there are any others).

Anyways +1 to merge this change.

**Comment by cstamas** [comment]
+1

**Pull request merged**
