### PR TITLE
Update to jline 1.0 which should support windows 32 and 64 bit

### PR DESCRIPTION
**Pull request by jdillon**
Update to jline 1.0 to get windows 64 bit dll support.

### CODE REVIEW

**Comment by jdillon** [comment]
Doesn't appear that jline 1.0 is functioning at all :-(

**Comment by jdillon** [comment]
Maybe it is working, but not in a "new-style" cygwin terminal... yup.  Old style and cmd.exe seems to be okay.

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
+1
We can live with new style cygwin terminal not working. Main thing Windows users have cmd prompt to use and it works.
If jline fixes new cygwin terminal support in future, we'll pick it up then.

**Pull request merged**
