### PR TITLE
Bump Jetty to latest 7.x

### PR DESCRIPTION
**Pull request by cstamas**
A lot of fixes in place since we bumped to then latest 7.4.5....

### CODE REVIEW

**Comment by velo** [comment]
+1

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
+1
Probably not 'required' but what about updating https://github.com/sonatype/sisu-jetty7/blob/develop/pom.xml

**Comment by cstamas** [comment]
Bumped sisu-jetty7

**Pull request merged**
