### PR TITLE
o Fix IT names to have them executed by failsafe

### PR DESCRIPTION
**Pull request by nabcos**
I spotted these a while ago, ITs not named *IT so they are not run in the CI build.

Reference build will be here: https://builds.sonatype.org/job/nexus-oss-its-feature/75/ (not yet started)

### CODE REVIEW

**Comment by velo** [comment]
+1

**Comment by peterlynch** [comment]
+1 wow

**Comment by cstamas** [comment]
+1

**Comment by bdemers** [comment]
+1

**Comment by nabcos** [comment]
new reference build https://builds.sonatype.org/job/nexus-oss-its-feature/81

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
CI votes -1 on one of the ITs, not sure yet why - works on my local machine :-/

**Comment by nabcos** [comment]
another feature build: https://builds.sonatype.org/job/nexus-oss-its-feature/91

**Comment by nabcos** [comment]
CI voted +1

**Pull request merged**
