### PR TITLE
Move nexus-test-harness/* to nexus-test/*

### PR DESCRIPTION
**Pull request by jdillon**

### CODE REVIEW

**Comment by peterlynch** [comment]
do we have feature build? gonna trust a feature build - looking at diff is pointless

**Comment by jdillon** [comment]
https://builds.sonatype.org/job/nexus-oss-its-feature/494/jdk=java-6x,label=linux: SUCCESS

Win failure was due to fail to get git log, slave04 needs to be reconnected.

**Comment by adreghiciu** [comment]
+1

**Comment by cstamas** [comment]
+1

**Pull request merged**
