### PR TITLE
Nexus Launcher and Utils improvements

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by peterlynch** [comment]
+1 should mention what issue # this relates to: NEXUS-4723?

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
@peterlynch It could be NEXUS-4723 but I actually did this while I refactored all tests from nexus bundle maker plugin to use nexus launcher.
BTW, tests are now much more nicer to read and easier to comprehend.

**Comment by adreghiciu** [comment]
Started feature build: https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/135/

**Comment by adreghiciu** [comment]
CI voted +1

**Pull request merged**
