### PR TITLE
Bump versions of nexus-launcher dependencies

### PR DESCRIPTION
**Pull request by adreghiciu**
Bump version of sisu-bundle-launcher to be able to use latest aether for ITs and sisu-jsw-utils to make ITs runnable also on windows

Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
:cake:

**Comment by velo** [comment]
Any related jira for this?
+1

**Comment by peterlynch** [comment]
why were they not runnable?

**Comment by adreghiciu** [comment]
@peterlynch Because we did not correctly set the jsw classpath property for teh jar that contain steh special launcher that is creating the sanity checks threads. Vlad changed that in jsw dependency and confirmed it works fine for him for insight ITs

**Comment by bdemers** [comment]
-1
Release the modules, then update the pom with the release version
(but +1 for updating the version to a released one)

**Comment by adreghiciu** [comment]
@bdemers is 2:1 I could merge this:D
Just kidding, actually that's why I did not merge, to check with more people

**Comment by peterlynch** [comment]
should add a jira explaining the change and add to the iteration.

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/180/

**Pull request merged**
