### PR TITLE
NEXUS-4801 Virtual repository attribute upgrade

### PR DESCRIPTION
**Pull request by cstamas**
Only File items were handled, but not Link items.

Every Items except Collection items has attributes saved.

### CODE REVIEW

**Comment by bdemers** [comment]
looks fine, but should have a test

**Comment by nabcos** [comment]
+1 pending tests

**Comment by velo** [comment]
+1 after CI touches this code.

**Comment by cstamas** [comment]
CI job:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/194/

**Comment by cstamas** [comment]
CI voted +1 (with one IT failing that failed on https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/186/ that it totally unrelated, so I am taking that one as "intermittent failure")

**Pull request merged**
