### PR TITLE
Add an system property option for setting test log level per test class name

### PR DESCRIPTION
**Pull request by adreghiciu**
The new option will allow for CI to specify problematic tests to be logged at debug level always. This will allow us that in case of a failure to be eventually get more details.

Example: -Dit.nexus.log.level.use.debug=Nexus3082*

Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/174/

**Comment by adreghiciu** [comment]
New CI feature build https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/175/

**Comment by adreghiciu** [comment]
CI voted +1

**Comment by nabcos** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by peterlynch** [comment]
+1 to the implementation
I expect we will have short memories remembering this mechanism exists.

**Comment by peterlynch** [comment]
Updated this page with the property. https://docs.sonatype.com/display/Nexus/Testing

**Pull request merged**
