### PR TITLE
Cleanup of ContentLocator related classes.

### PR DESCRIPTION
**Pull request by cstamas**
Also, archetype content locator unnecessary object creation removed. Same for File LocalStorage.

### CODE REVIEW

**Comment by cstamas** [comment]
CI job queued:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/84/

**Comment by cstamas** [comment]
Hm, hudson swallowed job 84
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/

Now job 85 is queued

**Comment by nabcos** [comment]
+1

**Comment by velo** [comment]
+

**Pull request merged**
