### PR TITLE
Introducing new events

### PR DESCRIPTION
**Pull request by cstamas**
Related to NXCM-4606

### CODE REVIEW

**Comment by adreghiciu** [comment]
This events are fine but do we need them now? Maybe we wait with this till we have a proper solution to proxy a group problem as in the one you described where slave will create a group and sync member changes

**Comment by cstamas** [comment]
I think we do need them, at least to prevent Staging using/extending RepositoryItemBatchEventAdded directly, and let it extend RepositoryItemBatchEventAddedToGroup instead.

**Comment by jdillon** [comment]
Does this fix something that is currently problem after Alin's change to even ordering yesterday?

If not, then -1 to avoid adding this to solve a problem which is fixed already.

**Comment by peterlynch** [comment]
related to NXCM-4606, but is this required for 2.3?

**Comment by ifedorenko** [comment]
-1. agreed on fix for nxcm-4606 does not require these events.

**Comment by cstamas** [comment]
Closing for now

**Pull request closed without merging**
