### PR TITLE
Archetype update

### PR DESCRIPTION
**Pull request by mosabua**
Small comment to add grid repo and updated compiler plugin (used ancient version before).

### CODE REVIEW

**Comment by cstamas** [comment]
:beer:

**Comment by peterlynch** [comment]
I missed why central is not enough?

**Comment by mosabua** [comment]
This is what you get with central only.. https://gist.github.com/4048052

**Comment by peterlynch** [comment]
ok as long as https://builds.sonatype.org/view/nexus/job/nexus-oss-its-external-developer/ eventually passes, which mimics what an external developer will do

**Comment by peterlynch** [comment]
+1

**Comment by mosabua** [comment]
Well... the change did not affect that and the build is currently broken anyway :-(

**Pull request merged**
