### PR TITLE
[NEXUS-5349] Use HC4 to check if Nexus is started in ITs

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
Not really needed, but... https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/464/

**Comment by cstamas** [comment]
+1

**Comment by nabcos** [comment]
Where did all the waitFor muck go? was it unused?
+1

**Comment by adreghiciu** [comment]
@nabcos unused. That class was copied from some class of Nexus. Now is properly made only for this purpose

**Comment by jdillon** [comment]
+1 thx @adreghiciu

**Pull request merged**
