### PR TITLE
NXCM-4852: EOF on deploy

### PR DESCRIPTION
**Pull request by cstamas**
Introduced new LocalStorage Exception to mark this, and translating it on REST level to some other status that 500 Server Error, that automagically kicks in on those response codes.

### CODE REVIEW

**Comment by ifedorenko** [comment]
-1

Need to verify partially downloaded files are not left behind.

**Comment by cstamas** [comment]
CI
https://bamboo.zion.sonatype.com/browse/NXO-OSSF36-1

**Comment by cstamas** [comment]
CI +1'd

**Comment by nabcos** [comment]
+1

**Comment by ifedorenko** [comment]
+1

**Pull request merged**
