### PR TITLE
Updated to plexus-task-scheduler:1.4.3

### PR DESCRIPTION
**Pull request by bentmann**
You liked its snapshot? Now get the real thing!

### CODE REVIEW

**Comment by bentmann** [comment]
Currently staged at https://repository.sonatype.org/content/repositories/sonatype_org-011/

**Comment by dbradicich** [comment]
+1
and an extra +1 for comedic value ;)

**Comment by velo** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by bentmann** [comment]
Merged in 30cea0bf28cc86a90e9ed232487ef626471d4090

**Pull request closed without merging**
