### PR TITLE
NEXUS-4823: quick fix for Resin, use Guice form of @Inject

### PR DESCRIPTION
**Pull request by mcculls**
Scheduled CI: https://builds.sonatype.org/job/nexus-oss-its-feature/198/

### CODE REVIEW

**Comment by jdillon** [comment]
ugly, but if its fixes the problem +1.
Is that the only use of @ Inject which it has issues with?

**Comment by mcculls** [comment]
Yes, as far as I can tell Resin only scans the filter instance - for other scanning (ie. inside the WAR) you need to configure web-beans.xml. Unfortunately I couldn't find any way to stop Resin from eagerly reacting to the JSR330 form of @Inject in the filter instance and throwing an unrecoverable error, hence this kludge.

**Comment by cstamas** [comment]
:beer:

**Comment by bdemers** [comment]
ugg, but +1

**Pull request merged**
