### PR TITLE
o [NEXUS-4669] LVO plugin fixes

### PR DESCRIPTION
**Pull request by nabcos**
- following redirects with proxy enabled did not work with AHC for some reason. Solved by fixing NXCM-3565, reverting to apache httpclient
- js did not have a reference to the currently running version anymore, so UI did not even check REST resource
- added tests for the classes used in production

reference build: https://builds.sonatype.org/job/nexus-oss-feature/15/
ITs not needed, as the main problem lay within the javascript parts and only UTs added.

### CODE REVIEW

**Comment by nabcos** [comment]
new build: https://builds.sonatype.org/job/nexus-oss-feature/17

previous failed because of undeployed changes to server-provider

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
CI voted +1

**Comment by cstamas** [comment]
+1

**Pull request merged**
