### PR TITLE
NEXUS-5241: Simple fix

### PR DESCRIPTION
**Pull request by cstamas**
A simple fix fixing the issue, easily backportable to 2.1 line too.

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
If we have a whitelist of things to include, do we need a way for plugins to contribute to that whitelist? The exclusions are for maven-specific things (which is still in nexus-core, by chance), what about p2/obr/nuget/yum/ruby?

EDIT: actually a blacklist might also need plugin contributions

**Comment by cstamas** [comment]
Exactly that is the "proper" fix. This fix is just a shortcut that is
easily backportable to 2.1.x

Thanks,
~t~ mobile

**Comment by nabcos** [comment]
OK, I did not get that. Should we merge this only to 2.1.x then, and leave the issue open for 2.2?

**Pull request merged**
