### PR TITLE
Warn when magic annotations (@ExtensionPoint @Managed) kick in

### PR DESCRIPTION
**Pull request by jdillon**
Logs warnings when components are reliant on the ExtensionPoint and Managed "magic" instead of properly using Named and Singleton.

Logs detected Plexus components as DEBUG too, once we are close to killing Plexus completely we can flip this to WARN.

### CODE REVIEW

**Comment by peterlynch** [comment]
+1 for the idea

**Comment by peterlynch** [comment]
How much debug logging will this spill out?

Want to avoid filling up customer logs with DEBUGs with this when they are trying to find some other problem.

**Comment by jdillon** [comment]
It will spit out a bit of DEBUG on bootup warning about Plexus components (only once at bootup, not constantly), otherwise it shouldn't spit out anything as I've been fixing components as I find them.

**Comment by jdillon** [comment]
I wonder if I should also warn about use of legacy com.google.inject.\* annotations.

**Comment by mosabua** [comment]
I am sure it would help some devs.

**Pull request merged**
