### PR TITLE
[NEXUS-3427] Manually save null values for user agent customization and additional query params

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/351/

**Comment by nabcos** [comment]
+1

**Comment by cstamas** [comment]
:beer:

**Comment by peterlynch** [comment]
+1

**Comment by adreghiciu** [comment]
CI voted +1 (failing tests are unrelated)

**Pull request merged**
