### PR TITLE
[NEXUS-5110] Show scheduled tasks menu item just based on the fact that user has read privilege

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
+1

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
operations accessible from this menu are protected on server side as well?

**Comment by adreghiciu** [comment]
Dunno, but would be stupid not to be ;)

More, the operations are not permmited from UI as add/delete/save buttons are disabled when no rights

**Pull request merged**
