### PR TITLE
NEXUS-4628: added "resolution" to lastRequested update

### PR DESCRIPTION
**Pull request by cstamas**
The initial implementation only for review.

Added UTs too. Ready for votes.

### CODE REVIEW

**Comment by velo** [comment]
too late, 57 already merged ;)

**Comment by velo** [comment]
+1
but I would appreciate less code format changes  ☻

**Comment by cstamas** [comment]
Rebase happened against current master and UTs added.

**Comment by nabcos** [comment]
+1

**Comment by bdemers** [comment]
+1 but don't forget the performance tests

**Comment by bdemers** [comment]
Also the issue says 12 hours.  I'm not saying 24 is bad, we just need to agree, then update one or the other.

**Comment by cstamas** [comment]
True, issue said 12h. Fixing the default value in a moment and will merge this.

**Comment by cstamas** [comment]
Ah, backing up: while the issue _does mention_ 12h as "resolution", the "Evict unused proxied items" task on UI allows configurations in _days_ (24h). So, IMO, it does not make sense to have lastRequest have more grained "resolution" then a day...

**Comment by bdemers** [comment]
One could make an argument that it would make a [minor] difference.  Personally I don't care, just as long as the jira issue is updated.

**Pull request merged**
