### PR TITLE
[NEXUS-5414] Do not process proxy repositories in snapshots removal task

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://bamboo.zion.sonatype.com/browse/NXO-OSSF26-1/

**Comment by adreghiciu** [comment]
CI :+1:

**Comment by cstamas** [comment]
+1

**Comment by nabcos** [comment]
+1

**Pull request merged**
