### PR TITLE
Nexus bootstrap

### PR DESCRIPTION
**Pull request by jdillon**
Add nexus-bootstrap module with custom simplified launcher

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by peterlynch** [comment]
+1 because I understand this work to directly benefit writing more tests and more stable tests - and it looks similar to what Matrix had which proved fairly stable

**Comment by cstamas** [comment]
+1

**Comment by jdillon** [comment]
Pending some sanity checks about compat with new nexus test launcher and existing it framework and then we are good to merge.

**Comment by jdillon** [comment]
https://builds.sonatype.org/job/nexus-oss-its-feature/365/ PASSED

**Comment by peterlynch** [comment]
just checking - are we waiting for @jdillon to have time to merge this after installer work?

**Comment by adreghiciu** [comment]
I brought nexus-bootstrap up to date (merging master into it) and after building tested if nexus capabilities and usertoken that have ITs bsed on nexus launcher. Everything works fine. Actually it should not affect those ITs as nexus launcher is not changed to take in count the changes from nexus-bootstrap.

Bottom line, merging this brach can be done as there is no impact on nexus-launcher test or the legacy ITs (this is proven by its feature build)

**Pull request merged**
