### PR TITLE
NEXUS-4811: use Plexus XML to scope test templates

### PR DESCRIPTION
**Pull request by mcculls**
Used test specific Plexus XML to make sure the test template components were limited to the Nexus4807 test. The ability to limit scanning to a subset of the test classes is a missing feature in the current Sisu test support that should be investigated for the next major release.

### CODE REVIEW

**Comment by velo** [comment]
+1

**Comment by cstamas** [comment]
:beer: :beer:

**Comment by mcculls** [comment]
Kicked off CI: https://builds.sonatype.org/job/nexus-oss-its-feature/185/

**Comment by bdemers** [comment]
+1

**Comment by nabcos** [comment]
+1

**Pull request merged**
