### PR TITLE
REVIEW: Move timeline ui

### PR DESCRIPTION
**Pull request by nabcos**
When the timeline was changed to be a plugin, the UI code was left in core. This change sets up timeline plugin to contribute its own UI.

This change is not for 2.4, and should be considered at the start of 2.4.1 or 2.5

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1 on the move

**Comment by nabcos** [comment]
Rebased because of conflict with unrelated changes in master (r.js config).

**Comment by kellyrob99** [comment]
+1

**Comment by jdillon** [comment]
looks okay, be sure to update @since before merging

+1

**Pull request merged**
