### PR TITLE
NEXUS-4873 - Fix UT

### PR DESCRIPTION
**Pull request by velo**
Small UT fix, download index task now throws exception if it fail to download the index.

### CODE REVIEW

**Comment by velo** [comment]
Ci in progress
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/235/

**Comment by mcculls** [comment]
+1

**Comment by mcculls** [comment]
The right CI link appears to be https://builds.sonatype.org/job/nexus-oss-its-feature/236/ - which passed

**Comment by velo** [comment]
yeap
236 ci +1

**Comment by cstamas** [comment]
So, merge it!

**Comment by nabcos** [comment]
+1

**Pull request merged**
