### PR TITLE
Launcher enhancements

### PR DESCRIPTION
**Pull request by adreghiciu**
There are more areas I worked on:
1. Make possible to run nexus ITs against multiple versions of nexus as a parametrized junit test. To do so, an IT must subclass NexusParametrizedITSupport/NexusRunningParametrizedITSupport and can provide nexus bundle coordinates in two ways: hardcoded in IT or via parameters file. Be default the parameters will be looked up from a file. 
   The NexusITSupport.NexusRunningITSupport are still working as before.
   The parametrized nexus bundle launcher coordinates can contain placeholders such as ${project.version}, ${project.groupId}, ${project.artifactId} or any project property from pom. Another placeholder that can be used is ${project.dm.version} that will look up the value from dependency management. Some examples:
   "org.sonatype.nexus:nexus-oss-webapp:zip:bundle:2.1"
   "org.sonatype.nexus:nexus-oss-webapp:zip:bundle:${project.version}"
   "org.sonatype.nexus:nexus-oss-webapp:zip:bundle:${project.dm.version}"

Once we merge this to master I will write an guide on how to write ITs.
1. Split the IT support classes from nexus-launcher. The new module is nexus/nexus-test/nexus-testsuite-support. This is the dependency that has to be added to projects that want to make nexus launcher based ITs
   The new module is also having basic ITs for supported features.
2. Extract artifact resolver, file paths into utility classes so they can be reused if one decide to not extend the NexusITSupport.

Some of this changes will make some already  written ITs not compile but I'm willing to go through all of them and fix them as the fixes are trivial. And is better in my view to do this changes now when we have a few such tests then going on without doing this changes.

I also made a lot of small commits to easier follow the changes.

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/375/

**Comment by jdillon** [comment]
```
Another placeholder that can be used is ${project.dm.version} that will look up the value from dependency management
"org.sonatype.nexus:nexus-oss-webapp:zip:bundle:${project.dm.version}"
```

Any reason to not simply lookup from DM if there is no version configured instead of using a property for that?

```
"org.sonatype.nexus:nexus-oss-webapp:zip:bundle"
```

IMO we should be pulling as much information out of the pom as possible to reduce the chances of configuration getting out of sync.  And pulling from DM is IMO much more preferred than defining a bunch of version properties in a pom, and then configuring those properties in the test properties, which IMO seems like unneeded bloat since we have access to the pom and all of this information should already be captured there.

**Comment by adreghiciu** [comment]
Just to make things clear as I did not explain it before. Using "org.sonatype.nexus:nexus-oss-webapp:zip:bundle:${project.dm.version}" will not mean that there is any pom properties to be defined or configuring them in injected-test.properties. Is just a marker that we know that the wanted version is from dependency management.
We can also imply that if the version is not present to look it up from dependency management.

**Comment by jdillon** [comment]
I was pretty sure that is what you meant/how it worked.  Just seemed odd to use a property here for that, when the rest of maven tends to use dm when no version is configured.

**Comment by jdillon** [comment]
I do not see any of the launcher its running in the build you referenced.  Is this pull supposed to include its for the launcher bits and expect them to be running?

**Comment by adreghiciu** [comment]
@jdillon you are right. Somehow the ITs did not run. What is interesting is that we get some surefire failure while building the nexus-testsuite-support module that contains the ITs but the build did not fail. I will look into it, but this worries me.

**Comment by jdillon** [comment]
When I tried to configure these its to run before I ran into a lot of problems with the nexus project wanting to use testng for failsafe and that cased a shit-storm when trying to run these its.

IMO more reasons NOT to use testng...

**Comment by adreghiciu** [comment]
@jdillon Well I did run into problems with org.sonatype.nexus.integrationtests.report.ProgressListener as it was configured in parent poms and inherited in all places that wanted to run failsafe.But I solved that and locally running the its do not fail. Indeed I run the build with -pl nexus/nexus-test/nexus-tessuite-support. I will make a full build locally.
Still is strange to see surefire exceptions but the build to not fail...

**Comment by peterlynch** [comment]
consider writing the future documentation using a package.html to keep with the code - a la Mockito style - not sure people like that style, but I do find it handy when using Mockito in the IDE to have "the manual" right there.

**Comment by peterlynch** [comment]
remind me what TestNG is getting us these days for the ITs - JUnit categories are supposedly now supported by surefire to some extent... (caveat, surefire is usually buggy)

**Comment by jdillon** [comment]
I'm not 100% sure, but I don't think its used for anything that junit4 doesn't already provide.  IMO it just requires a lot of extra maven configuration to get surefire/failsafe to use it, which isn't compatible with junit4 execution.  Things would be a lot simpler if we just just used junit4 for everything.

**Comment by cstamas** [comment]
We should get back to Junit4. TestNG was just another huge mistake.

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/378/

@jdillon look in log of above build for:
Running org.sonatype.nexus.testsuite.support.StartAndStopNexusParametrizedFilteredIT

**Comment by adreghiciu** [comment]
@jdillon In https://github.com/sonatype/nexus/commit/88a4f2de2055327e82e7996648fc047d57aaa628 I added support for not specifying the version and automatically looking it up in DM

**Comment by cstamas** [comment]
+1

**Comment by peterlynch** [comment]
-1
nexus-oss-its had 1855 linux tests
nexus-oss-its-feature had 1810 linux tests

Your branch just deleted 45 tests?

**Comment by adreghiciu** [comment]
@peterlynch come on :) Do you really think so?
What about this feature build: https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/372/testReport/
Did we add 1855-1755=100 tests in 8 days?

**Comment by peterlynch** [comment]
lets just figure out the reason for the difference - maybe it's job config or something

**Comment by adreghiciu** [comment]
@peterlynch This build is done by the same time https://builds.sonatype.org/view/nexus/job/nexus-oss-its/357/ at the feature build I mention before. It has 1853 ITs.

**Comment by peterlynch** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its/357/

<table class="pane sortable"><tbody><tr><td class="pane-header"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Configuration Name<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Duration<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">All<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Failed<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Skipped<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td></tr><tr><td class="pane"><a href=".././jdk=java-6x,label=linux/testReport">jdk=java-6x,label=linux</a></td><td style="text-align:right" data="2304.6536" class="pane">38 min</td><td class="pane" style="text-align:right;">1853</td><td class="pane" style="text-align:right;">0</td><td class="pane" style="text-align:right;">7</td></tr><tr><td class="pane"><a href=".././jdk=java-6x,label=win/testReport">jdk=java-6x,label=win</a></td><td style="text-align:right" data="2830.9565" class="pane">47 min</td><td class="pane" style="text-align:right;">1853</td><td class="pane" style="text-align:right;">0</td><td class="pane" style="text-align:right;">7</td></tr></tbody></table>


https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/378/

<table width="100%" height="100%" border="0"><tbody><tr><td id="global-messages" width="100%"><div class="global-message"></div></td></tr><tr><td id="main-panel" width="100%" height="100%"><a name="skip2content"></a><h1>Test Result</h1><div><div>
          2 failures
          
            , 12 skipped
            </div><div style="width:100%; height:1em; background-color: #729FCF"><div style="width:0.055248618784530384%; height: 1em; background-color: #EF2929; float: left"></div><div style="width:0.3314917127071823%; height: 1em; background-color: #FCE94F; float: left"></div></div><div align="right">
          3,620 tests
          </div></div><table class="pane sortable"><tbody><tr><td class="pane-header"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Configuration Name<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Duration<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">All<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Failed<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Skipped<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td></tr><tr><td class="pane"><a href=".././jdk=java-6x,label=linux/testReport">jdk=java-6x,label=linux</a></td><td style="text-align:right" data="2444.87" class="pane">40 min</td><td class="pane" style="text-align:right;">1810</td><td class="pane" style="text-align:right;">0</td><td class="pane" style="text-align:right;">6</td></tr><tr><td class="pane"><a href=".././jdk=java-6x,label=win/testReport">jdk=java-6x,label=win</a></td><td style="text-align:right" data="4959.711" class="pane">1 hr 22 min</td><td class="pane" style="text-align:right;">1810</td><td class="pane" style="text-align:right;"><a href="#jdk=java-6x,label=win">2</a></td><td class="pane" style="text-align:right;">6</td></tr></tbody></table><br><h2>Failed Tests</h2><h3><a name="jdk=java-6x,label=win"></a><a href=".././jdk=java-6x,label=win/testReport">jdk=java-6x,label=win</a></h3><table class="pane sortable"><tbody><tr><td class="pane-header"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Test Name<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Duration<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td><td class="pane-header" style="width:4em"><a href="#" class="sortheader" onclick="ts_resortTable(this);return false;">Age<span class="sortarrow">&nbsp;&nbsp;&nbsp;</span></a></td></tr><tr><td class="pane"><a href=".././jdk=java-6x,label=win/testReport/org.sonatype.nexus.integrationtests.nexus977/Nexus977GroupOfGroupsIncrementalIndexIT/validateIncrementalIndexesCreated/">org.sonatype.nexus.integrationtests.nexus977.Nexus977GroupOfGroupsIncrementalIndexIT.validateIncrementalIndexesCreated&nbsp;</a></td><td class="pane" style="text-align:right;">565.495</td><td class="pane" style="text-align:right;">1</td></tr><tr><td class="pane"><a href=".././jdk=java-6x,label=win/testReport/org.sonatype.nexus.integrationtests.nexus1650/Nexus1650MultipleManualTaskIT/testMultipleManualInstances/">org.sonatype.nexus.integrationtests.nexus1650.Nexus1650MultipleManualTaskIT.testMultipleManualInstances&nbsp;</a></td><td class="pane" style="text-align:right;">5.811</td><td class="pane" style="text-align:right;">1</td></tr></tbody></table></td></tr></tbody></table>


I think we should explain the difference in number of tests before merge. We should also at least explain why feature build is taking longer than non feature build on windows. Could have nothing to do with your changes, or maybe so....

**Comment by jdillon** [comment]
@adreghiciu ya, I see tests running now for testsuite.support in #378 good :-)

**Comment by jdillon** [comment]
http://www.evernote.com/shard/s18/sh/e52f4d1c-c73b-4383-a324-2c971d15070e/9038faafe612e8f19c2727155253c895

**Comment by jdillon** [comment]
+1 to merge

**Pull request merged**
