### PR TITLE
o [NEXUS-4809] Consume released jetty-testsuite

### PR DESCRIPTION
**Pull request by nabcos**
https://builds.sonatype.org/job/nexus-oss-its-feature/189/
https://builds.sonatype.org/job/nexus-oss-its-feature/192/

### CODE REVIEW

**Comment by adreghiciu** [comment]
Just remind you that you will not go through with a SNAPSHOT dependency. So, you will have to make a release to be able to consume it and merge to master.
I do not agree with that, but seems that is the policy lately. In my view, as Tamas says for the projects we control we should be able to use SNAPSHOTS for a finite amount of time so we do not release until we validate it.

**Comment by bdemers** [comment]
+1 pending using a  released version

**Comment by nabcos** [comment]
CI voted sort-of +1 (intermittent failure on lnx, win built ok)

**Comment by velo** [comment]
+1

**Pull request merged**
