### PR TITLE
Use litmus avoid injection

### PR DESCRIPTION
**Pull request by jdillon**
Improvements to tests.

Going to leave this pull asis, will fix others later... way too much for a single pull.

### CODE REVIEW

**Comment by peterlynch** [comment]
1

**Comment by jdillon** [comment]
Looks like this is causing a few tests to fail downstream in nexus-proxy... atm unsure why.

**Comment by jdillon** [comment]
dropped last commit, unrelated to test impl changes, and setting workingDirectory causes issues, will sort out other changes in other commits to clean up profiles.

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
setting workingDirectory remains an issue with sonar generating proper test coverage so glad you avoid that here - will need to look into fixing patching sonar to do the right thing because setting jacoco.exec report path does not help

**Comment by peterlynch** [comment]
+1

**Pull request merged**
