### PR TITLE
Log timing of http remote requests made by Nexus

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
@peterlynch first we get this in and then we can document it

**Comment by peterlynch** [comment]
@adreghiciu sure was more of a reminder

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
+1 on @cstamas changes

**Comment by peterlynch** [comment]
+1 its good

**Comment by jdillon** [comment]
I think this would have been better implemented with something like javasimon, which adds more detail and has the ability to be exposed via jmx.

Its used by an aspect in smartproxy for reference:

https://github.com/sonatype/nexus-smartproxy-plugin/blob/master/nexus-smartproxy-plugin/src/main/java/com/sonatype/nexus/plugins/smartproxy/internal/TimingAspect.java

**Pull request merged**
