### PR TITLE
o [NEXUS-4579] Let remove from MetadataHelper use snapshot removers DeleteOperation setting

### PR DESCRIPTION
**Pull request by nabcos**
Original pull (https://github.com/sonatype/nexus/pull/72) missed this codepath.

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by velo** [comment]
+1 but
"This pull request cannot be automatically merged."....

**Comment by nabcos** [comment]
Branch rebased with master, as one commit was needed to fix IT failing on master. Only test-related "changes" (same changes, different commits), production diff is the same.

**Comment by adreghiciu** [comment]
+1

**Comment by bdemers** [comment]
+1

**Comment by nabcos** [comment]
"sort of" successful build, only unstable/unrelated failures:
https://builds.sonatype.org/job/nexus-oss-its-feature/58/

**Pull request merged**
