### PR TITLE
Logging updates

### PR DESCRIPTION
**Pull request by jdillon**

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
Related pulls:

https://github.com/sonatype/sisu-restlet-bridge/pull/5
https://github.com/sonatype/nexus-enterprise/pull/284
https://github.com/sonatype/sonatype-licensing/pull/20

**Comment by cstamas** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Pull request merged**
