### PR TITLE
o [NEXUS-4679] Fix validation message key for duplicate repository IDs

### PR DESCRIPTION
**Pull request by nabcos**
If no explicite key is used for validation errors, the REST reply will have numerical IDs that do not match field names and will not be displayed anywhere.

### CODE REVIEW

**Comment by nabcos** [comment]
reference build will be https://builds.sonatype.org/job/nexus-oss-its-feature/96

**Comment by velo** [comment]
+1

**Comment by bdemers** [comment]
Can you add a test for these conditions (there should be existing similar tests)
Other then that it looks good

**Comment by peterlynch** [comment]
+1 we really need javascript tests but that is a different story ;)

**Comment by nabcos** [comment]
interesting. https://builds.sonatype.org/job/nexus-oss-its-feature/96 sat in queue for 3 days and started building just now, so the build will use latest test changes as well.

**Comment by nabcos** [comment]
CI voted +1

**Pull request merged**
