### PR TITLE
Fixed test to account for platform-specific differences in line terminat...

### PR DESCRIPTION
**Pull request by bentmann**
...ors of source files

### CODE REVIEW

**Comment by velo** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by cstamas** [comment]
-1, no, a Veto, lu! This source should not be built on Windows! :D

:beer:

**Comment by bentmann** [comment]
I was already wondering why I couldn't find a windows CI job for nexus-oss ;-)

**Comment by cstamas** [comment]
Sorry for closing this by mistake!

**Pull request merged**
