### PR TITLE
[NEXUS-4980] Fix DTD to jetty@Eclipse

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/307/

**Comment by nabcos** [comment]
+1

**Comment by cstamas** [comment]
+1, but the `/examples` dir is about to be thrown away... (and probably move into separate OSS git repo to have them still)

**Comment by adreghiciu** [comment]
Build 307 voted +1 on linux but did not start at all on win
Starting another one https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/309/

**Comment by adreghiciu** [comment]
CI on linux voted +1, win failed with unrelated problem. Merging.

**Pull request merged**
