### PR TITLE
Make OSS LDAP plugin use new crypto plugin

### PR DESCRIPTION
**Pull request by cstamas**

### CODE REVIEW

**Comment by nabcos** [comment]
+1

**Comment by cstamas** [comment]
CI
https://bamboo.zion.sonatype.com/browse/NXO-OSSF15-1

**Comment by cstamas** [comment]
CI +1'd
https://bamboo.zion.sonatype.com/browse/NXO-OSSF15-2

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
