### PR TITLE
Removed url from plugins that don't really have a site

### PR DESCRIPTION
**Pull request by velo**
UI already handle this just fine.

### CODE REVIEW

**Comment by peterlynch** [comment]
:beer:

**Comment by velo** [comment]
https://github.com/sonatype/nexus-enterprise/pull/180

**Comment by jdillon** [comment]
Is simply to remove the default generated url from parent no?  Perhaps the parent should omit its url so that plugins don't have to put this empty tag in to override it?

I admit I tend to remove these as they don't clearly provide any reason to exist...

**Comment by velo** [comment]
No, if you remove from top level maven add a /${lower-lever-artifactId}....

**Comment by jdillon** [comment]
I've no clue what your comment means @velo

**Comment by velo** [comment]
Top level pom
<url></url>

Plugin pom
no url entry

Effective plugin pom (what maven sees after all CoC is applied)
<url>/plugin</url>

**Pull request merged**
