### PR TITLE
NXCM-3792, changing header image name, simple way to force browser to reload images use by new theme.

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by velo** [comment]
screen shot:
https://issues.sonatype.org/secure/attachment/52172/Screen+Shot+2012-01-27+at+12.29.58+PM.png

nice! +1

**Comment by jdillon** [comment]
merge

**Comment by cstamas** [comment]
:cake:

**Comment by mcculls** [comment]
+1

**Pull request merged**
