### PR TITLE
[NEXUS-4723[ Make REST test utility classes reusable via nexus-launcher

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by cstamas** [comment]
Looks fine, but a sidenote: we have similar case as with commons-io, is not a direct dependency of core (it gets in as transitive one), but tests (both UT/IT) are for some reason extensively using it (even if 99% of equivalent methods are present in plexus utils).

This same stands for indexer-artifact. Classes like Gav are not present in core anymore (the Maven Indexer Gav, while Nexus got it's own equiv class), but tests (mostly ITs) are still using it...

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
Kicked off feature build: https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/128/

**Comment by adreghiciu** [comment]
@cstamas I might miss something here, but I do not get the connection between your comment and this pull request

**Comment by cstamas** [comment]
It was just a fyi "Maven Indexer Gav classes are used", just I realized while looking at the diffs. Not related to this pull req at all.

**Comment by adreghiciu** [comment]
@cstamas Got it now. Well, I just used the current functionality so no change in that direction.

**Comment by adreghiciu** [comment]
The build https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/128/ was passing with only one test failing which is also failing for master build.
I consider that CI voted +1

**Comment by cstamas** [comment]
:kiss:

**Pull request merged**
