### PR TITLE
Rename *LRTest to *IT. They will be run by failsafe

### PR DESCRIPTION
**Pull request by adreghiciu**
Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/390/

**Comment by jdillon** [comment]
+1

**Comment by adreghiciu** [comment]
Changes are not complete. The modules having those tests will have to be setup to run the failsafe plugin, or move them to nexus/nexus-test-harness/nexus-test-harness-its

**Comment by jdillon** [comment]
Likely should add an it profile to flip on failsafe, which can cover any module in the tree.

https://github.com/sonatype/nexus-usertoken/blob/master/pom.xml#L348

**Comment by nabcos** [comment]
+1 (also for profile)

**Comment by cstamas** [comment]
+1 (and a :beer: if profile done)

**Comment by adreghiciu** [comment]
@cstamas unfortunatelly the profile is not enough. running the LRTests as Its via failsafe fails with an error about some components that could not be found. Yet I did not had time to look into it byt maybe you know more about those plexus components setup

**Comment by cstamas** [comment]
This files are ancient UTs using PlexusTestCase. Plexus Test Case has a possibility to "sniff in" extra components.xml file that has _same binary name_ as UT class is, but extension ".xml". Like this one here:
https://github.com/sonatype/nexus/blob/master/nexus/nexus-proxy/src/test/resources/org/sonatype/nexus/proxy/maven/metadata/RecreateMavenMetadataWalkerLRTest.xml

Now, if you _rename_ the Java classes, you _have to_ rename the corresponding XML files too, otherwise they will be not loaded by PlexusTestCase and hence, environment will not be set as expected....

**Comment by peterlynch** [comment]
PlexusTestCase is evil. +1 to the rest + profile

**Comment by adreghiciu** [comment]
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/396/

**Comment by adreghiciu** [comment]
CI failed with 3 unrelated tests

**Comment by peterlynch** [comment]
Noticed this:

Running org.sonatype.nexus.proxy.attributes.DefaultAttributeStorageTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 56.555 sec

Perhaps should be IT

**Pull request merged**
