### PR TITLE
NEXUS-4695 - Using 'text-area' component provided by nexus core

### PR DESCRIPTION
**Pull request by velo**
To test this I changed groovy plugin to use the new 'text-area'.

Since I have the work done I decided to push it here.

### CODE REVIEW

**Comment by adreghiciu** [comment]
Just asking. Wasn't the removed JS provided some additional features? Was all that in there just for making a simple text area?

**Comment by velo** [comment]
@adreghiciu the additional JS was not being used...

**Comment by adreghiciu** [comment]
+1 then

**Comment by nabcos** [comment]
+1

**Pull request merged**
