### PR TITLE
NEXUS-4205 - set content validation to true

### PR DESCRIPTION
**Pull request by velo**
Enable fileTypeValidation by default for new proxy repositories and for the proxy's that ship in the default configuration.

### CODE REVIEW

**Comment by cstamas** [comment]
And how about

``` java
    public boolean isFileTypeValidation()
    {
+        return Boolean.valueOf( getNodeValue( getRootNode(), FILE_TYPE_VALIDATION, "true" ) );
-        return Boolean.valueOf( getNodeValue( getRootNode(), FILE_TYPE_VALIDATION, "false" ) );
    }
```

in AbstractProxyRepositoryConfiguration that renders all these changes (and those in nexus-enterprise, and also those in P2 and OBR plugins) unneeded. Also, this is more correct, since this change makes sure UTs will receive same defaults as ITs are, while with changing templates only (and nexus.xml) the change is visible in ITs only....

**Comment by cstamas** [comment]
-1 pull back and redo with change above please

**Comment by velo** [comment]
Done

**Comment by nabcos** [comment]
Do we still need all those configuration/template changes when the default value is set correctly?

**Comment by cstamas** [comment]
No, all we need is f8b851261ef8ff19cb8488514f6250197f1e14cf and nothing more. No change in Nexus EE or OBR or P2 plugin is needed either.

**Comment by velo** [comment]
Ok, I closed nexus ee, obr and p2 pull request.

**Comment by cstamas** [comment]
☺

**Comment by velo** [comment]
BTW, added a missing conversion at rest api

**Comment by velo** [comment]
I assume tamas smile face counts as +1 =D

**Pull request merged**
