### PR TITLE
[NEXUS-5667] Update to ExtJS 3.4.1.1

### PR DESCRIPTION
**Pull request by nabcos**
Update to ExtJS 3.4.1.1 plus IE10 compatibility

### CODE REVIEW

**Comment by kellyrob99** [comment]
+1
Are there any specific Jiras you know about that should be tested against this?

**Comment by nabcos** [comment]
I only know of NEXUS-5597, which is fixed by this pull. There is one known issue that I did not file yet, because I forgot to take a screenshot: Checkboxes are missing their "upper bound", visible space seems to be one pixel short.

**Comment by kellyrob99** [comment]
Thanks Ben.

**Comment by jdillon** [comment]
cursory testing of oss build shows no apparent problems
- mac chrome 26.0.1410.65
- mac safari 6.0.3
- mac firefox 19.0.2
- winxp ie8
- win7 ie9
- win9 ie10

+1

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
