### PR TITLE
Nexus unit tests cleanup

### PR DESCRIPTION
**Pull request by adreghiciu**
I did a bunch of cleanup related to Nexus unit tests.
I tried to make small commits so every change is explained.
I run the CI build for this and the tests are passing.

If you guys agree with this changes, before merges there are a few of changes that has to be made to nexus enterprise UTs, but those are small and can be done in 30min(is) max.

### CODE REVIEW

**Comment by cstamas** [comment]
+1 wow!

**Comment by bdemers** [comment]
Great cleanup!

**Comment by peterlynch** [comment]
+1 Do it! ...thanks for cleaning this up for your sanity and ours.

**Comment by adreghiciu** [comment]
Merged to master

**Pull request closed without merging**
