### PR TITLE
[NXCM-4395] Add jsoup to handle parsing out non-OK response entities int...

### PR DESCRIPTION
**Pull request by jdillon**
...o something more reasonable to present to users.

https://issues.sonatype.org/browse/NXCM-4395

### CODE REVIEW

**Comment by adreghiciu** [comment]
+1 beside system.out

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
I'd like to see a test for this. As it is I have to manually go test what it does.

**Comment by cstamas** [comment]
+1

**Pull request merged**
