### PR TITLE
Cleanup profiles

### PR DESCRIPTION
**Pull request by jdillon**
Clean up profiles, makes default mvn clean install not run its.  Locally -Dtest=skip runs in ~3.5 min, with uts takes ~9.5 min.  Will start up a local -Dit and see if anything else needs to be updated.

### CODE REVIEW

**Comment by jdillon** [comment]
its almost run, pending an issue with TestProperties

**Comment by jdillon** [comment]
With -Dit locally this passes:

```
[INFO] Nexus : Test Harness : Core ITs ................... SUCCESS [1:19:06.133s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1:47:51.181s
[INFO] Finished at: Sat Oct 20 17:16:17 PDT 2012
[INFO] Final Memory: 113M/439M
[INFO] ------------------------------------------------------------------------
```

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
Why did you open #600 when it contains all commits of this branch and not continued work here? Just to separate changes?

Changes seem sane, I ran builds for #599 and #600, but not with full ITs yet.

**Comment by jdillon** [comment]
@nabcos btw there was a progression of changes, each built on top of the other.   There was way too much to just drop in once pull request.  Once we get the smaller pulls (like this one, blessed and merged) then it will be clearer what the changes are the the other pulls... was the only way I could think to get a lot of stuff done but get it reviewed as well.

**Comment by nabcos** [comment]
+1

**Pull request merged**
