### PR TITLE
Upgrade to Shiro 1.2 (does not include switching to Guice-based config)

### PR DESCRIPTION
**Pull request by mcculls**
CI in progress: https://builds.sonatype.org/job/nexus-oss-its-feature/jdk=java-6x,label=linux/302/
( unfortunately the windows build wasn't able to start due to IOException connecting to slave02 )

### CODE REVIEW

**Comment by jdillon** [comment]
+1

**Comment by cstamas** [comment]
:beer:

I believe these are minimal changes needed to make it work. When will be all the cruft removed? Thinking all the "session-less" stuff, that is provided out of the box by Shiro in 1.2....

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Comment by mcculls** [comment]
wrt remaining cruft, other changes are coming soon...

**Comment by mcculls** [comment]
CI votes +1: https://builds.sonatype.org/job/nexus-oss-its-feature/306/

**Pull request merged**
