### PR TITLE
o [NXCM-3544] Use content class name for the repository view privileges

### PR DESCRIPTION
**Pull request by nabcos**
Screenshot attached to issue NXCM-3544.

### CODE REVIEW

**Comment by cstamas** [comment]
:cake:

**Comment by mcculls** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Comment by bdemers** [comment]
+1

**Comment by nabcos** [comment]
unrelated IT failure in feature build:
https://builds.sonatype.org/job/nexus-oss-its-feature/144/

**Pull request merged**
