### PR TITLE
Update to the latest 1.1.1 (same as 1.0 other then parent pom version and license header fixes)

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by bdemers** [comment]
Pending CI build, which might be: https://builds.sonatype.org/job/nexus-oss-its-feature/184/

**Comment by velo** [comment]
+1

**Comment by nabcos** [comment]
+1

**Comment by peterlynch** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
