### PR TITLE
o [NEXUS-4064] Fix menu actions to display when a repo does not publish the URL

### PR DESCRIPTION
**Pull request by nabcos**

### CODE REVIEW

**Comment by cstamas** [comment]
+1

**Comment by peterlynch** [comment]
+1 so now all menu items display despite url not being published?

**Comment by nabcos** [comment]
Yes, there is no difference repos with published/unpublished URL.

There is one weird behavior that's no regression:
For 'unpublished' repos, you get no context menu in the lower pane, when you right click on artifacts. The method that assembles the menu is never called, didn't want to debug that just now. (It's the same behavior for 2.1/2.0.6).

**Comment by peterlynch** [comment]
> For 'unpublished' repos, you get no context menu in the lower pane, when you right click on artifacts. The method that
> assembles the menu is never called, didn't want to debug that just now. (It's the same behavior for 2.1/2.0.6).

Ok. Issue filed for that? we can push that out in another release.

**Comment by nabcos** [comment]
https://issues.sonatype.org/browse/NEXUS-5146

**Pull request merged**
