### PR TITLE
Extract Hc4ProviderBase superclass from Hc4ProviderImpl

### PR DESCRIPTION
**Pull request by adreghiciu**
This makes possible to reuse the functionality without all the extra cruft

Needed by ssl plugin to retrieve certificates using all the proxy/auth/params from global/repository repository context

Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
+1 seems reasonable, but a bit confusing that base and impl classes are both components....

**Comment by ifedorenko** [comment]
+1

**Comment by adreghiciu** [comment]
https://bamboo.zion.sonatype.com/browse/NXO-OSSF23-1

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
CI :+1: (one unrelated failure)

**Pull request merged**
