### PR TITLE
NXCM-4052: Fixes

### PR DESCRIPTION
**Pull request by cstamas**

### CODE REVIEW

**Comment by cstamas** [comment]
Scheduled CI (but hudson cannot tell job no in advance, one job already runs).

**Comment by cstamas** [comment]
CI job is:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/300/

But win already failed with already reported regression:
https://issues.sonatype.org/browse/NEXUS-4785

**Comment by peterlynch** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Pull request merged**
