### PR TITLE
Implement a nexus client for server configuration

### PR DESCRIPTION
**Pull request by adreghiciu**
For now only http proxy supported. Rest of configuration will be added as needed.

Signed-off-by: Alin Dreghiciu adreghiciu@gmail.com

### CODE REVIEW

**Comment by cstamas** [comment]
+1 but how about authc support too (fine if not yet needed), as username/pw for proxy...

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
@cstamas review

**Comment by cstamas** [comment]
:beer:

**Comment by nabcos** [comment]
is there  a UT with an optional segment? I find that structure with optional segments etc. a little confusing, but in general +1

**Comment by adreghiciu** [comment]
JerseyHttpProxyTest is also testing that as part of testing HttpProxy

**Pull request merged**
