### PR TITLE
NXCM-3690 - Removed google repository

### PR DESCRIPTION
**Pull request by velo**
Removed google svn repository from default nexus configuration

### CODE REVIEW

**Comment by velo** [comment]
Please also review https://github.com/sonatype/nexus-enterprise/pull/100

**Comment by bdemers** [comment]
+1 
both look fine, just start an it feature job to verify there are no tests that count the number or repos

**Comment by velo** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/171/

**Comment by nabcos** [comment]
+1 (just address the build job failure)

**Comment by velo** [comment]
CI +1
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/172/

The failed test seems random, I will address it as well

**Comment by peterlynch** [comment]
+1 after CI gives +1

**Comment by velo** [comment]
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/173/
+1

**Pull request merged**
