### PR TITLE
Simple change to make ITs work

### PR DESCRIPTION
**Pull request by cstamas**
Minimal change in AppContext story needed for ITs to work.

As Plexus tries to copy the passed in map (instead of delegating to it as SISU does),
now passing in the flattened AppContext as context.

Also, implemented nexus and nexus-test property file
loading, since they are optional (last ctor param is false, if not
found it will be silently ignored).

### CODE REVIEW

**Comment by cstamas** [comment]
CI job started:
https://builds.sonatype.org/view/nexus-features/job/nexus-oss-its-feature/425/

**Comment by adreghiciu** [comment]
+1 Tested via central secure ITs

**Comment by adreghiciu** [comment]
CI voted +1

**Comment by ifedorenko** [comment]
+1

**Pull request merged**
