### PR TITLE
NEXUS-5087: Bump Aether version to 1.13.1

### PR DESCRIPTION
**Pull request by cstamas**

### CODE REVIEW

**Comment by cstamas** [comment]
CI:
https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/355/

**Comment by cstamas** [comment]
Both CI slaves voted +1, but job failed at the end, since there are two files with missing headers (coming from master, from the added archetype).

**Comment by adreghiciu** [comment]
+1

**Comment by nabcos** [comment]
+1

**Pull request merged**
