### PR TITLE
[NEXUS-4695] Add support for multiline (text area) form field

### PR DESCRIPTION
**Pull request by adreghiciu**

### CODE REVIEW

**Comment by adreghiciu** [comment]
CI build triggered: https://builds.sonatype.org/job/nexus-oss-its-feature/111/

**Comment by nabcos** [comment]
+1

**Comment by adreghiciu** [comment]
New build as the other one I started with wrong params https://builds.sonatype.org/job/nexus-oss-its-feature/112/

**Comment by bdemers** [comment]
+1

**Comment by adreghiciu** [comment]
CI voted +1

**Pull request merged**
