### PR TITLE
[NEXUS-4782] Add jetty-jmx jar + example configuration

### PR DESCRIPTION
**Pull request by jdillon**
Adds the jetty-jmx jar + examples/jetty-jmx.xml to the bundle

### CODE REVIEW

**Comment by velo** [comment]
+1

**Comment by cstamas** [comment]
:cake:

**Comment by adreghiciu** [comment]
+1

**Comment by mcculls** [comment]
+1

**Comment by rseddon** [comment]
-1

The jetty-jmx.xml file is missing configuration information for Nexus.  This is inconsistent with the other files in the examples directory.

**Comment by jdillon** [comment]
I was not sure how these files were intended to be used, easy to update however.  But IMO this is a bit strange, since if you need any 2 of these features, you are screwed for this "copy to jetty.xml" to install.  The default jetty server's behavior to allow loading 1 or more xml files is much better.

**Comment by peterlynch** [comment]
since this does not start a RMI connector server, why not just add this to the default jetty.xml?

**Comment by rseddon** [comment]
+1 
looks good now

**Pull request merged**
