### PR TITLE
License headers

### PR DESCRIPTION
**Pull request by peterlynch**
bulk alignment of license headers and nexus-aggregator pom extending forge-parent

https://bamboo.zion.sonatype.com/browse/NXO-OSSF24-1

Expect this to only be merged if all ITs pass ( in case header was formatted on wrong file ) and will not cause too much disruption for team.

### CODE REVIEW

**Comment by peterlynch** [comment]
https://bamboo.zion.sonatype.com/browse/NXO-OSSF24-2

**Comment by peterlynch** [comment]
thinking I better do this on the weekend..last chance...

**Comment by jdillon** [comment]
/me shrugs

go for it

**Comment by peterlynch** [comment]
one final build of it
https://bamboo.zion.sonatype.com/browse/NXO-OSSF24-3

**Comment by peterlynch** [comment]
branch failed on known unstable test yet to be fixed

**Pull request merged**
