### PR TITLE
Get the OSS ITs passing again

### PR DESCRIPTION
**Pull request by mcculls**

### CODE REVIEW

**Comment by adreghiciu** [comment]
The so called UTs are also suffering form the same problem. They pass because for some of them I put scanning to ON so we may want to do the same thing = making the NexusTestSupport use SCANNING_INDEX and make a search for test specified set of scanning and drop it

**Comment by adreghiciu** [comment]
for the rest +1

**Comment by adreghiciu** [comment]
And forgot to mention that we may wanna search also PRO for "custom" setting of scanning as I bet is not needed if there is any place that does that.

**Comment by mcculls** [comment]
Which UTs? - I assume Pro since the OSS UTs all pass at the moment

**Comment by adreghiciu** [comment]
the OSS ones. The pass but they pass because for those that fail I put SCANNING_ON

**Comment by adreghiciu** [comment]
Look for SCANNING_CACHE in NexusTestSupport and for example SimpleRealmTest.I would say that we should look for all places that does set configuration.setClassPathScanning( PlexusConstants.SCANNING_ON ); and remove that method, of course beside NexusTestSupport

**Comment by cstamas** [comment]
+1 for scanning index, but unsure why shading of other than -core lucene artifacts is needed. I think this will be gone once lucene-core is removed from core (about to: https://github.com/sonatype/nexus/pull/116 )

**Comment by mcculls** [comment]
Classloading - all the lucene artifacts are on the IT classpath, by only shading core into the plugin we appear to get into a situation where lucene-highlight sees two different lucene-core classes (presumably from the IT classpath vs the plugin). Not sure what class lookup approach lucene follows, but it could be the root cause why it ends up with this split view. Shading all lucene artifacts into the plugin avoids this because then it appears to find them first.

Properly removing lucene-core from nexus core should help (and reduce the need for the IT classpath tampering) - I just needed a stable build for testing, hence this patch ;)

**Comment by cstamas** [comment]
Agreed, +1 for both then

**Pull request merged**
