### PR TITLE
using 1.6.0-SNAPSHOT scheduler

### PR DESCRIPTION
**Pull request by dbradicich**

### CODE REVIEW

**Comment by bdemers** [comment]
+1 but release it first :D

**Comment by dbradicich** [comment]
staged 1.6.0 release and updated the branch to use it

**Comment by cstamas** [comment]
:beer:

**Comment by nabcos** [comment]
CI build?

**Comment by velo** [comment]
+1 after CI +1

**Comment by dbradicich** [comment]
https://builds.sonatype.org/job/nexus-oss-its-feature/191/

Few failures, though I was unsure if because of anything i changed, so i ran ITs locally and all passed ok (except for few that failed becaue of inability to download maven dependencies from fake-central as the sha1 files had invalid checksums, or should say file endings changed on some poms to make the sha1 different)

**Comment by nabcos** [comment]
This is not related to scheduler but worries me, @cstamas can you take a look?
(https://builds.sonatype.org/job/nexus-oss-its-feature/191/jdk=java-6x,label=linux/testReport/junit/org.sonatype.nexus.integrationtests.nexus2797/Nexus2797Validate140TaskUpgradeIT/oncePerClassSetUp/,
the actual failure is ".../target/nexus/nexus-work-dir/proxy/attributes unable to be deleted.")

```
Exception in thread "LegacyAttributesUpgrader" java.lang.NullPointerException
    at org.sonatype.nexus.proxy.maven.LayoutConverterShadowRepository.getMasterRepository(LayoutConverterShadowRepository.java:102)
    at org.sonatype.nexus.proxy.maven.LayoutConverterShadowRepository.getMasterRepository(LayoutConverterShadowRepository.java:54)
    at org.sonatype.nexus.proxy.repository.AbstractShadowRepository.getLocalStatus(AbstractShadowRepository.java:124)
    at org.sonatype.nexus.proxy.attributes.upgrade.AttributeUpgraderThread.run(AttributeUpgraderThread.java:114)
```

The other failure is obscure, as that NPE is in `@AfterMethod`, and basically says that `@BeforeMethod` did not run - and the failure is logged twice on hudson...

```
java.lang.NullPointerException
    at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:973)
    at org.sonatype.nexus.integrationtests.nexus4579.Nexus4579OptionalTrashForSnapshotsIT.cleanTrash(Nexus4579OptionalTrashForSnapshotsIT.java:106)
```

But this IT is actually testing a task (snapshot remover), and my guess is this NPE is shadowing the real failure coming from two of the `@Test` methods.

**Comment by adreghiciu** [comment]
@dbradicich what is in 1.6 we need?

**Comment by bdemers** [comment]
+1

**Comment by dbradicich** [comment]
@adreghiciu The fixes put in place so that we dont schedule Future instances before task is done completion, rather do it afterwards (though the next run time is still persisted before hand so data isn't lost).  This includes issues of tasks getting duplicated (not config, but multiple threads running same task)

**Pull request closed without merging**
