### PR TITLE
NXCM-3593, fixing headers for test resources

### PR DESCRIPTION
**Pull request by bdemers**

### CODE REVIEW

**Comment by bdemers** [comment]
Running IT's to check if we validate any hashes
https://builds.sonatype.org/job/nexus-oss-its-feature/177/

**Comment by bdemers** [comment]
Take 2: https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/178/

**Comment by peterlynch** [comment]
fear the diff!
Its going to be bad news if license headers in test files break tests.
+1 as long as ITs pass
sandbox should be moved out - it is just noise

**Comment by nabcos** [comment]
sandbox is an svn remainder, nowadays those projects would rot in peace in their own git repositories.

one test broke, but rightfully so: https://github.com/sonatype/nexus/pull/227/files#diff-38
+1 pending fix

**Comment by velo** [comment]
+1

**Comment by adreghiciu** [comment]
+1

**Comment by bdemers** [comment]
here we go again: https://builds.sonatype.org/view/nexus/job/nexus-oss-its-feature/179/

**Pull request merged**
