### PR TITLE
WIP: Add basic registration of mbeans

### PR DESCRIPTION
**Pull request by jdillon**
Sandbox to sort out how to best enable general use of JMX inside of Nexus.

### CODE REVIEW

**Comment by jdillon** [comment]
atm these are brain-dead simple mbeans, but with a bit more effort we can make them dynamic and really useful.

**Comment by peterlynch** [comment]
headed in the right direction +1

**Comment by adreghiciu** [comment]
+1

**Comment by jdillon** [comment]
Really need to sort out MXBean use as well as make some support to dynamically expose beans to avoid all the standard MBean muck.   ATM I'm only using standard MBeans to identify key bits which should be added as mbeans.

Probably also need to sort out a general MBean naming strategy.

**Comment by peterlynch** [comment]
status?

**Comment by jdillon** [comment]
This is still a WIP, I think there are better ways to handle this simpler, using jmxutils... so atm on hold until some of the other clean up settles down, and then I'll look at it again.

**Comment by jdillon** [comment]
BTW, I'm thinking this might be better handled in an aspect weaved in at compile time. 

Some of the other timing-based code might also be better done in this manner as well.

**Comment by jdillon** [comment]
Will reconsider after we have AOP support in NX how to add JMX generally to various components.

**Pull request closed without merging**
