### PR TITLE
The column model for the repo list grid is now built in array before pan...

### PR DESCRIPTION
**Pull request by dbradicich**
...el is created, then an event is spawned so plugins can mangle the column model (and toolbar) if necessary

### CODE REVIEW

**Comment by peterlynch** [comment]
what issue is this related too and what impact will these changes have?

**Comment by peterlynch** [comment]
+1

**Comment by dbradicich** [comment]
ya sorry, didnt know the initial ticket number when i started the changes ;)  but just to add extension points for the health check plugin to have its way with the grid

**Comment by nabcos** [comment]
+1

**Pull request merged**
